# -*- coding: utf-8 -*-
"""hmm_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFetnj0GEyQXhB4ihLdWNKDOVZwNIoBE
"""

import numpy as np
from .inference import forward_backward_log, viterbi_log, loglik_logB

class HMMModel:
    def __init__(self, K, emission, random_state=0, eps=1e-8):
        self.K = K
        self.emission = emission
        self.eps = eps
        self.rng = np.random.default_rng(random_state)

        self.pi = np.full(K, 1.0 / K)
        self.A  = np.full((K, K), 1.0 / K)

    def fit(self, X, n_iter=20, tol=1e-3, verbose=False):
        T = X.shape[0]   
        prev = -np.inf
        for it in range(n_iter):
            log_B = self.emission.log_B(X)
            if verbose:
                assert np.isfinite(log_B).all(), "log_B has NaN/inf"
                assert log_B.max() < 500, f"log_B too large: max={log_B.max()}"  

            gamma, xi, logL, _, _ = forward_backward_log(log_B, self.pi, self.A, eps=self.eps)
            if verbose:
                assert np.isfinite(gamma).all()
                assert np.allclose(gamma.sum(axis=1), 1.0, atol=1e-3)
                assert np.isfinite(xi).all()
                assert np.isfinite(logL)


            # M-step for pi, A
            eps = self.eps
            self.pi = gamma[0] + eps
            self.pi /= self.pi.sum()

            self.A = xi.sum(axis=0) + eps
            self.A /= self.A.sum(axis=1, keepdims=True)

            assert np.isfinite(self.pi).all() and np.isfinite(self.A).all(), "pi/A has NaN/inf"
            assert (self.pi >= -1e-8).all() and abs(self.pi.sum() - 1.0) < 1e-6, "pi invalid"
            assert (self.A >= -1e-8).all(), "A has negative values"
            assert np.allclose(self.A.sum(axis=1), 1.0, atol=1e-6), "A rows not normalized"


            # M-step for emission
            self.emission.m_step(X, gamma)

            if verbose and it > 0:
                drop = logL - prev
                assert drop > -1500, f"logL dropped too much: {drop}"

            if verbose:
                delta = logL - prev if it > 0 else np.nan
                print(f"iter {it+1:02d}, logL={logL:.3f}, ΔlogL={delta:.3f}, Δ/T={(delta/T if it>0 else np.nan):.6g}")



            if it > 0 and abs((logL - prev) / T) < tol:
                break
            prev = logL
        return self

    def score(self, X):
        log_B = self.emission.log_B(X)
        return loglik_logB(log_B, self.pi, self.A, eps=self.eps)

    def viterbi(self, X):
        log_B = self.emission.log_B(X)
        return viterbi_log(log_B, self.pi, self.A, eps=self.eps)