# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1om8IkwhdQtu-mjMuk32WY4wxmbmUWlPN
"""

import numpy as np
from .utils import logsumexp

def forward_backward_log(log_B, pi, A, eps=1e-12):
    """
    log-space FB
    log_B: (T,K)
    pi: (K,)
    A: (K,K)
    return: gamma (T,K), xi (T-1,K,K), logL (scalar), alpha (T,K), beta (T,K)
    """
    T, K = log_B.shape
    log_pi = np.log(pi + eps)
    log_A  = np.log(A + eps)

    alpha = np.zeros((T, K), dtype=float)
    alpha[0] = log_pi + log_B[0]
    for t in range(1, T):
        temp = alpha[t-1][:, None] + log_A      # (K,K)
        alpha[t] = log_B[t] + logsumexp(temp, axis=0)

    logL = logsumexp(alpha[-1], axis=0)

    beta = np.zeros((T, K), dtype=float)
    beta[-1] = 0.0
    for t in range(T-2, -1, -1):
        temp = log_A + log_B[t+1] + beta[t+1]   # (K,K)
        beta[t] = logsumexp(temp, axis=1)

    # gamma
    log_gamma = alpha + beta - logL
    gamma = np.exp(log_gamma)
    gamma /= gamma.sum(axis=1, keepdims=True)

    # xi
    xi = np.zeros((T-1, K, K), dtype=float)
    for t in range(T-1):
        temp = (alpha[t][:, None] + log_A + log_B[t+1][None, :] + beta[t+1][None, :] - logL)
        xi[t] = np.exp(temp)
        s = xi[t].sum()
        if s > 0:
            xi[t] /= s

    return gamma, xi, float(logL), alpha, beta

def viterbi_log(log_B, pi, A, eps=1e-12):
    """
    log-space Viterbi
    """
    T, K = log_B.shape
    log_pi = np.log(pi + eps)
    log_A  = np.log(A + eps)

    delta = np.zeros((T, K), dtype=float)
    psi = np.zeros((T, K), dtype=int)

    delta[0] = log_pi + log_B[0]
    for t in range(1, T):
        temp = delta[t-1][:, None] + log_A
        psi[t] = np.argmax(temp, axis=0)
        delta[t] = log_B[t] + np.max(temp, axis=0)

    states = np.zeros(T, dtype=int)
    states[-1] = np.argmax(delta[-1])
    for t in range(T-2, -1, -1):
        states[t] = psi[t+1, states[t+1]]
    return states

def loglik_logB(log_B, pi, A, eps=1e-12):
    """
    只算 log-likelihood（forward）
    """
    T, K = log_B.shape
    log_pi = np.log(pi + eps)
    log_A  = np.log(A + eps)

    alpha = np.zeros((T, K), dtype=float)
    alpha[0] = log_pi + log_B[0]
    for t in range(1, T):
        temp = alpha[t-1][:, None] + log_A
        alpha[t] = log_B[t] + logsumexp(temp, axis=0)
    return float(logsumexp(alpha[-1], axis=0))