# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XO5Jz35FTtHXs4QhV2kbtSuSOHfJEX1c
"""

# hmm_pkg/utils.py
import numpy as np
from .emissions import ChowLiuEmission

def logsumexp(a, axis=None, keepdims=False):
    a = np.asarray(a)
    a_max = np.max(a, axis=axis, keepdims=True)
    if np.isneginf(a_max).all():
        out = -np.inf
        if keepdims:
            return out
        return np.squeeze(out, axis=axis) if axis is not None else out
    out = a_max + np.log(np.sum(np.exp(a - a_max), axis=axis, keepdims=True))
    if not keepdims and axis is not None:
        out = np.squeeze(out, axis=axis)
    return out

def save_chowliu_hmm(model, path, **meta):
    """
    Save HMM + Chow–Liu emission parameters to npz.
    model must have: pi, A, emission.p1_all, emission.edges_all, emission.pair_probs_all
    """
    np.savez(
        path,
        pi=model.pi,
        A=model.A,
        p1_all=model.emission.p1_all,
        edges_all=model.emission.edges_all,
        pair_probs_all=model.emission.pair_probs_all,
        **meta
    )

def load_chowliu_hmm(path):
    """
    Load HMM + Chow–Liu emission from npz and rebuild a usable model.
    NOTE: import HMMModel inside function to avoid circular import.
    """
    data = np.load(path, allow_pickle=True)

    # You must have saved these meta fields
    K = int(data["N_MODES"])
    N = int(data["N"])

    em = ChowLiuEmission(
        K=K,
        N=N,
        random_state=int(data["random_state"]),
        eta=float(data["eta"]),
        alpha=float(data["alpha"]),
    )
    em.p1_all = data["p1_all"]
    em.edges_all = data["edges_all"]
    em.pair_probs_all = data["pair_probs_all"]
    # Do NOT read this field here; it crashes in this environment
    #em.pair_probs_all = None

    # Lazy import to break circular dependency
    from .hmm_models import HMMModel

    model = HMMModel(K, em, random_state=int(data["random_state"]))
    model.pi = data["pi"]
    model.A = data["A"]
    return model
