# -*- coding: utf-8 -*-
"""discriminability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjWAZkG4ceJ_lJmrquqImiH7eU-7SS93
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np
from numpy.typing import ArrayLike, NDArray

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

def _as_2d_float(X: ArrayLike) -> NDArray[np.float64]:
    X = np.asarray(X, dtype=np.float64)
    if X.ndim != 2:
        raise ValueError(f"X must be 2D (n_samples, n_features), got shape={X.shape}")
    return X


def _as_1d_int(modes: ArrayLike) -> NDArray[np.int64]:
    m = np.asarray(modes)
    if m.ndim != 1:
        raise ValueError(f"modes must be 1D, got shape={m.shape}")
    return m.astype(np.int64, copy=False)

def split_modes(
    X: ArrayLike,
    modes: ArrayLike,
    alpha: int,
    beta: int,
) -> Tuple[NDArray[np.float64], NDArray[np.float64]]:
    """
    Return X_alpha, X_beta where modes==alpha/beta.
    """
    X = _as_2d_float(X)
    m = _as_1d_int(modes)

    if len(m) != X.shape[0]:
        raise ValueError(f"len(modes) must match X.shape[0]; got {len(m)} vs {X.shape[0]}")

    X_alpha = X[m == int(alpha)]
    X_beta = X[m == int(beta)]
    return X_alpha, X_beta


def lda_projection_1d(
    X_alpha: ArrayLike,
    X_beta: ArrayLike,
    *,
    solver: str = "svd",
    shrinkage: Optional[str] = None,
    random_state: Optional[int] = None,
) -> Tuple[np.ndarray, np.ndarray, LinearDiscriminantAnalysis]:
    """
    Fit LDA on two classes and return 1D projections (Z_alpha, Z_beta) plus fitted model.
    """
    Xa = _as_2d_float(X_alpha)
    Xb = _as_2d_float(X_beta)

    X_ab = np.vstack([Xa, Xb])
    y_ab = np.hstack([np.zeros(len(Xa), dtype=int), np.ones(len(Xb), dtype=int)])

    lda = LinearDiscriminantAnalysis(
        n_components=1,
        solver=solver,
        shrinkage=shrinkage,
    )
    if hasattr(lda, "random_state"):
        lda.random_state = random_state

    Z = lda.fit_transform(X_ab, y_ab).ravel()
    Z_alpha = Z[: len(Xa)]
    Z_beta = Z[len(Xa) :]
    return Z_alpha, Z_beta, lda

def dprime_from_projections(Z_alpha: ArrayLike, Z_beta: ArrayLike, *, eps: float = 1e-12) -> float:
    Za = np.asarray(Z_alpha, dtype=np.float64).ravel()
    Zb = np.asarray(Z_beta, dtype=np.float64).ravel()

    va = Za.var(ddof=1) if len(Za) > 1 else 0.0
    vb = Zb.var(ddof=1) if len(Zb) > 1 else 0.0
    denom = np.sqrt(0.5 * (va + vb) + eps)
    return float(np.abs(Za.mean() - Zb.mean()) / denom)

def mode_dprime(
    X: ArrayLike,
    modes: ArrayLike,
    alpha: int,
    beta: int,
    *,
    min_samples: int = 3,
    solver: str = "svd",
    shrinkage: Optional[str] = None,
    random_state: Optional[int] = None,
) -> float:
    """
    d' between two modes using 1D LDA projection.
    Returns np.nan if either class has < min_samples.
    """
    X_alpha, X_beta = split_modes(X, modes, alpha, beta)

    if len(X_alpha) < min_samples or len(X_beta) < min_samples:
        return float("nan")

    Z_alpha, Z_beta, _ = lda_projection_1d(
        X_alpha, X_beta, solver=solver, shrinkage=shrinkage, random_state=random_state
    )
    return dprime_from_projections(Z_alpha, Z_beta)

@dataclass(frozen=True)
class NearestNeighborDiscriminabilityResult:
    dmins: np.ndarray          # shape (n_valid_modes,)
    mean_ks: np.ndarray        # shape (n_valid_modes,)
    valid_modes: np.ndarray    # which alphas were included

def nearest_neighbor_discriminability(
    X: ArrayLike,
    modes: ArrayLike,
    *,
    K: Optional[int] = None,
    min_samples: int = 3,
    mean_k_fn: str = "sum",
    solver: str = "svd",
    shrinkage: Optional[str] = None,
    random_state: Optional[int] = None,
) -> NearestNeighborDiscriminabilityResult:
    """
    For each mode alpha, compute d'_min over beta!=alpha.
    Also compute <k> per mode as a simple summary of mean spike word.
      - mean_k_fn="sum": mean(x).sum()
      - mean_k_fn="mean": mean(x).mean()
    """
    X = _as_2d_float(X)
    m = _as_1d_int(modes)

    if K is None:
        K = int(m.max()) + 1

    dmins = []
    mean_ks = []
    valid = []

    for alpha in range(int(K)):
        Xa = X[m == alpha]
        if len(Xa) < min_samples:
            continue

        d_list = []
        for beta in range(int(K)):
            if beta == alpha:
                continue
            d = mode_dprime(
                X, m, alpha, beta,
                min_samples=min_samples,
                solver=solver,
                shrinkage=shrinkage,
                random_state=random_state,
            )
            if not np.isnan(d):
                d_list.append(d)

        if len(d_list) == 0:
            continue

        dmins.append(float(np.min(d_list)))

        mu = Xa.mean(axis=0)
        if mean_k_fn == "sum":
            mean_ks.append(float(mu.sum()))
        elif mean_k_fn == "mean":
            mean_ks.append(float(mu.mean()))
        else:
            raise ValueError("mean_k_fn must be 'sum' or 'mean'")

        valid.append(alpha)

    return NearestNeighborDiscriminabilityResult(
        dmins=np.asarray(dmins, dtype=np.float64),
        mean_ks=np.asarray(mean_ks, dtype=np.float64),
        valid_modes=np.asarray(valid, dtype=np.int64),
    )