# -*- coding: utf-8 -*-
"""dominance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDmXYPyX9eInsIa3YaKaV0ohsrk2eZDH
"""

from __future__ import annotations
import numpy as np

def compute_mode_cell_probs(
    X: np.ndarray,
    modes: np.ndarray,
    K: int,
    eps: float = 1e-9,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Compute per-mode firing probability, global firing probability, and enrichment ratio.

    Parameters
    ----------
    X : (T, N) array_like of {0,1}
        Binary spike matrix.
    modes : (T,) array_like of int
        Mode/state assignment per time bin (0..K-1).
    K : int
        Number of modes.
    eps : float
        Small constant to avoid division by zero.

    Returns
    -------
    m_mode : (K, N) ndarray
        m_mode[k, i] = P(X_i=1 | mode=k).
    m_global : (N,) ndarray
        m_global[i] = P(X_i=1) (global across all time).
    ratio : (K, N) ndarray
        ratio[k, i] = m_mode[k, i] / m_global[i].
        Interpretable as enrichment (dominance) factor of cell i in mode k.
    """
    X = np.asarray(X)
    modes = np.asarray(modes)

    if X.ndim != 2:
        raise ValueError(f"X must be 2D (T,N). Got shape {X.shape}.")
    if modes.ndim != 1:
        raise ValueError(f"modes must be 1D (T,). Got shape {modes.shape}.")

    T, N = X.shape
    if modes.shape[0] != T:
        raise ValueError(f"modes length {modes.shape[0]} != T {T}.")
    if K <= 0:
        raise ValueError("K must be positive.")

    X_int = (X > 0).astype(int)

    m_global = X_int.mean(axis=0) + eps  # (N,)
    m_mode = np.zeros((K, N), dtype=float)

    for k in range(K):
        idx = (modes == k)
        if np.any(idx):
            m_mode[k] = X_int[idx].mean(axis=0)

    ratio = m_mode / m_global[None, :]
    return m_mode, m_global, ratio

def dominated_mask(
    m_mode: np.ndarray,
    ratio: np.ndarray,
    theta: float,
    min_prob: float = 0.01,
) -> np.ndarray:
    """
    Compute dominated/enriched mask.

    A cell i is dominated by mode k if:
      ratio[k,i] >= theta  and  m_mode[k,i] >= min_prob

    Returns
    -------
    mask : (K, N) bool ndarray
    """
    if theta <= 0:
        raise ValueError("theta must be positive.")
    if min_prob < 0:
        raise ValueError("min_prob must be non-negative.")
    return (ratio >= theta) & (m_mode >= min_prob)

def dominance_counts(mask: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Given dominated mask (K,N), compute:
      cells_per_mode: (K,)
      modes_per_cell: (N,)
    """
    if mask.ndim != 2:
        raise ValueError("mask must be 2D (K,N).")
    cells_per_mode = mask.sum(axis=1)
    modes_per_cell = mask.sum(axis=0)
    return cells_per_mode, modes_per_cell

def scan_theta_stats(
    m_mode: np.ndarray,
    ratio: np.ndarray,
    thetas: np.ndarray,
    min_prob: float = 0.01,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Scan a range of theta and compute:
      avg_cells_per_mode(theta)
      avg_modes_per_cell(theta)

    Returns
    -------
    avg_cells_per_mode : (len(thetas),)
    avg_modes_per_cell : (len(thetas),)
    """
    thetas = np.asarray(thetas, dtype=float)
    avg_cells_per_mode = np.zeros_like(thetas, dtype=float)
    avg_modes_per_cell = np.zeros_like(thetas, dtype=float)

    for j, theta in enumerate(thetas):
        mask = dominated_mask(m_mode, ratio, theta=theta, min_prob=min_prob)
        cells_per_mode, modes_per_cell = dominance_counts(mask)
        avg_cells_per_mode[j] = cells_per_mode.mean()
        avg_modes_per_cell[j] = modes_per_cell.mean()

    return avg_cells_per_mode, avg_modes_per_cell