# -*- coding: utf-8 -*-
"""dwell.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kdcu76Ng3XCOGvheMZXHf1PevnYBORvU
"""

from __future__ import annotations
import numpy as np
from numpy.typing import ArrayLike
from typing import List

def compute_dwell_times(
    modes: ArrayLike,
    bin_size_s: float,
) -> List[np.ndarray]:
    """
    Compute dwell times for each HMM mode using run-length encoding.

    Parameters
    ----------
    modes : array-like, shape (T,)
        Mode index (0, 1, ..., K-1) for each time bin.
    bin_size_s : float
        Duration of a single time bin in seconds.

    Returns
    -------
    dwell_times_per_mode : list of np.ndarray
        A list of length K. The k-th element is a 1D array containing
        all dwell times (in seconds) for mode k.
    """
    modes = np.asarray(modes, dtype=int)
    if modes.ndim != 1:
        raise ValueError("modes must be a 1D array")

    T = len(modes)
    if T == 0:
        return []

    K = modes.max() + 1
    dwell_times_per_mode = [[] for _ in range(K)]

    current_mode = modes[0]
    run_len = 1

    for t in range(1, T):
        if modes[t] == current_mode:
            run_len += 1
        else:
            dwell_times_per_mode[current_mode].append(run_len * bin_size_s)
            current_mode = modes[t]
            run_len = 1

    # last segment
    dwell_times_per_mode[current_mode].append(run_len * bin_size_s)

    return [
        np.asarray(dt, dtype=float) if len(dt) > 0 else np.array([])
        for dt in dwell_times_per_mode
    ]

def check_dwell_consistency(
    dwell_times_per_mode: List[np.ndarray],
    bin_size_s: float,
    T_original: int,
) -> float:
    """
    Check consistency between original time bins and reconstructed dwell times.

    Returns
    -------
    diff : float
        T_original - reconstructed number of bins
        (should be 0 up to numerical precision)
    """
    reconstructed_bins = sum(dt.sum() / bin_size_s for dt in dwell_times_per_mode)
    return T_original - reconstructed_bins