# -*- coding: utf-8 -*-
"""mapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iH0k_n9brcC5BDSxgwvNkRcUQWfHv1rA
"""

from __future__ import annotations
from typing import Dict, Tuple, Any, Iterable
import numpy as np

Coord = Tuple[int, int]

def build_label_to_coord(channel_info: Iterable[Tuple[Coord, str]]) -> Dict[str, Coord]:
    return {label: coord for coord, label in channel_info}

def build_index_to_spatial(
    channel_unit_to_index: Dict[Tuple[int, int], int],
    hwid_to_el: Dict[int, str],
    channel_info,
):
    """
    Build index_to_spatial[idx] = {
        "channel": int,
        "unit": int,
        "electrode": str|None,
        "pos": (row,col)|None
    }
    """
    label_to_coord = build_label_to_coord(channel_info)

    index_to_spatial: Dict[int, Dict[str, Any]] = {}

    for (channel, unit), idx in channel_unit_to_index.items():
        electrode = hwid_to_el.get(channel, None)
        coord = label_to_coord.get(electrode, None)

        index_to_spatial[idx] = {
            "channel": channel,
            "unit": unit,
            "electrode": electrode,
            "pos": coord,
        }

    return index_to_spatial