# -*- coding: utf-8 -*-
"""modes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Opo6jJHTHeLBG9fpaWwbqzU-qV5bVBh
"""

from __future__ import annotations

import numpy as np
from scipy.special import gammaln

def summarize_modes(
    X: np.ndarray,
    modes: np.ndarray,
    K: int,
    dt: float = 0.01,
    eps: float = 1e-12,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Summarize discrete modes for binary spike trains.

    Parameters
    ----------
    X : (T, N) array_like of {0,1}
        Binary spike matrix.
    modes : (T,) array_like of int
        Mode/state label for each time bin, values in {0,...,K-1}.
        Typically from Viterbi decoding.
    K : int
        Number of modes/states.
    dt : float, default=0.01
        Bin width in seconds.
    eps : float, default=1e-12
        Numerical epsilon for entropy computation.

    Returns
    -------
    w_sorted : (K,) ndarray
        Mode weights (frequency) sorted descending.
    order : (K,) ndarray of int
        Indices mapping sorted modes -> original labels.
        i.e., sorted_mode_idx s corresponds to original label order[s].
    m_centroid : (K, N) ndarray
        Per-mode firing probability vector, sorted by w.
        m_centroid[s, i] = P(X_i=1 | mode = order[s]).
    k_bar : (K,) ndarray
        Average spike count per bin for each sorted mode.
    S_bits_s : (K,) ndarray
        Independent-Bernoulli entropy proxy in bits/s for each sorted mode.

    Notes
    -----
    - Entropy assumes conditional independence across neurons within a mode:
      S_bin = sum_i H2(p_i), then S_bits_s = S_bin / dt.
    - If a mode never occurs, its centroid stays 0 and entropy becomes 0.
    """
    X = np.asarray(X)
    modes = np.asarray(modes)

    if X.ndim != 2:
        raise ValueError(f"X must be 2D (T,N). Got shape {X.shape}.")
    if modes.ndim != 1:
        raise ValueError(f"modes must be 1D (T,). Got shape {modes.shape}.")

    T, N = X.shape
    if modes.shape[0] != T:
        raise ValueError(f"modes length {modes.shape[0]} != T {T}.")
    if K <= 0:
        raise ValueError("K must be positive.")
    if dt <= 0:
        raise ValueError("dt must be positive.")

    # ensure binary-ish
    X_int = (X > 0).astype(int)

    # 1) weights
    w = np.array([(modes == k).mean() for k in range(K)], dtype=float)
    order = np.argsort(-w)          # descending
    w_sorted = w[order]

    # 2) centroids
    m_centroid = np.zeros((K, N), dtype=float)
    for k in range(K):
        idx = (modes == k)
        if np.any(idx):
            m_centroid[k] = X_int[idx].mean(axis=0)
    m_centroid = m_centroid[order]

    # 3) avg spike count per bin
    k_bar = m_centroid.sum(axis=1)

    # 4) entropy proxy (independent Bernoulli)
    S_bits_bin = np.zeros(K, dtype=float)
    for s in range(K):
        p = m_centroid[s]
        mask = (p > 0) & (p < 1)
        pc = p[mask]
        if pc.size == 0:
            S_bits_bin[s] = 0.0
        else:
            H2 = -np.sum(pc * np.log2(pc + eps) + (1 - pc) * np.log2(1 - pc + eps))
            S_bits_bin[s] = float(H2)

    S_bits_s = S_bits_bin / dt
    return w_sorted, order, m_centroid, k_bar, S_bits_s

def compute_Smax_combinatorial(
    k_bar: np.ndarray,
    N: int,
    dt: float = 0.01,
) -> np.ndarray:
    """
    Combinatorial upper bound on entropy: S_max(bin) = log2 C(N, k).

    We round k_bar to nearest integer k and compute log2 binomial coefficient
    using gammaln for numerical stability.

    Parameters
    ----------
    k_bar : (K,) array_like
        Average spike count per bin (can be non-integer).
    N : int
        Number of neurons.
    dt : float, default=0.01
        Bin width in seconds.

    Returns
    -------
    Smax_bits_s : (K,) ndarray
        S_max in bits/s.
    """
    k_bar = np.asarray(k_bar, dtype=float)
    if k_bar.ndim != 1:
        raise ValueError("k_bar must be 1D.")
    if N <= 0:
        raise ValueError("N must be positive.")
    if dt <= 0:
        raise ValueError("dt must be positive.")

    k_int = np.rint(k_bar).astype(int)
    k_int = np.clip(k_int, 0, N)

    logC = gammaln(N + 1) - gammaln(k_int + 1) - gammaln(N - k_int + 1)
    Smax_bits_bin = logC / np.log(2.0)
    return Smax_bits_bin / dt

def compute_Smax_gamma(k_bar, N, dt=0.01):
    k_bar = np.asarray(k_bar, dtype=float)
    k_bar = np.clip(k_bar, 0, N)

    log_num = gammaln(N + 1)
    log_den = gammaln(N - k_bar + 1) + gammaln(k_bar + 1)

    Smax_bits_bin = (log_num - log_den) / np.log(2.0)
    Smax_bits_s = Smax_bits_bin / dt
    return Smax_bits_s
    
def normalized_entropy_ratio(
    Smax_bits_s: np.ndarray,
    S_bits_s: np.ndarray,
    eps: float = 1e-12,
) -> np.ndarray:
    """
    Compute S_max / S with safe division.

    Parameters
    ----------
    Smax_bits_s : (K,)
    S_bits_s : (K,)
    eps : float

    Returns
    -------
    ratio : (K,)
        ratio = Smax / max(S, eps)
    """
    Smax_bits_s = np.asarray(Smax_bits_s, dtype=float)
    S_bits_s = np.asarray(S_bits_s, dtype=float)
    return Smax_bits_s / np.maximum(S_bits_s, eps)


def chowliu_entropy_rate_all_modes(
    p1_all,
    edges_all,
    pair_probs_all,
    dt,
    eps=1e-12,
):
    """
    Compute Chow–Liu entropy rate (bits/s) for each mode.

    Parameters
    ----------
    p1_all : (K, N) array
        Node marginals p1_all[k,i] = P(x_i=1 | z=k)
    edges_all : list of length K
        edges_all[k] is a list of (i,j) edges for mode k
    pair_probs_all : list of length K
        pair_probs_all[k] is a dict {(i,j): 2x2 joint table}
        table[a,b] = P(x_i=a, x_j=b)
    dt : float
        Time bin size (seconds)
    eps : float
        Numerical epsilon

    Returns
    -------
    S_bits_s : (K,) ndarray
        Entropy rate per mode in bits/s
    """
    p1_all = np.asarray(p1_all, dtype=float)
    K, N = p1_all.shape

    S_bits_bin = np.zeros(K, dtype=float)

    for k in range(K):
        p1 = np.clip(p1_all[k], eps, 1 - eps)

        # 1) Sum of node entropies
        H_nodes = -np.sum(
            p1 * np.log2(p1) + (1 - p1) * np.log2(1 - p1)
        )

        # 2) Subtract mutual information on tree edges
        I_sum = 0.0
        for (i, j) in edges_all[k]:
            # get joint table with correct orientation
            if (i, j) in pair_probs_all[k]:
                P = pair_probs_all[k][(i, j)]
            elif (j, i) in pair_probs_all[k]:
                P = pair_probs_all[k][(j, i)].T
            else:
                raise KeyError(f"Edge ({i},{j}) not found for mode {k}")

            # marginals
            pi1 = p1[i]
            pj1 = p1[j]
            pi0 = 1 - pi1
            pj0 = 1 - pj1

            # mutual information
            for a, pa in enumerate([pi0, pi1]):
                for b, pb in enumerate([pj0, pj1]):
                    pab = P[a, b]
                    if pab > 0:
                        I_sum += pab * np.log2((pab + eps) / (pa * pb + eps))

        S_bits_bin[k] = H_nodes - I_sum

    # convert to bits/s
    return S_bits_bin / dt

