# -*- coding: utf-8 -*-
"""mode_cluster_psth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZJabufmgX_w76zFImTgotdAPg5j9BNu
"""

from __future__ import annotations
import numpy as np
from numpy.typing import ArrayLike
from typing import Optional, Tuple

def core_cells_from_dominance(dominated_mask: ArrayLike, frac: float = 0.3) -> np.ndarray:
    """
    dominated_mask: (K, N) bool/int
    frac: e.g. 0.3 means >= 0.3*K modes dominated -> core cell

    returns: core_idx (1D int array)
    """
    D = np.asarray(dominated_mask)
    if D.ndim != 2:
        raise ValueError("dominated_mask must be 2D (K, N)")
    K, N = D.shape
    modes_per_cell = D.sum(axis=0)  # (N,)
    thr = int(np.ceil(frac * K))
    return np.where(modes_per_cell >= thr)[0]

def build_tau(T: int, start_bin_global: ArrayLike, bins_per_cond: ArrayLike, bin_size_s: float) -> np.ndarray:
    """
    tau[t] = time since onset within its condition segment (sec)
    """
    start_bin_global = np.asarray(start_bin_global, dtype=int)
    bins_per_cond = np.asarray(bins_per_cond, dtype=int)
    tau = np.zeros(T, dtype=float)
    for k in range(len(bins_per_cond)):
        off = int(start_bin_global[k])
        nb = int(bins_per_cond[k])
        tau[off:off+nb] = np.arange(nb) * float(bin_size_s)
    return tau

def build_contrast_per_bin(
    T: int,
    sel_indices: ArrayLike,
    start_bin_global: ArrayLike,
    bins_per_cond: ArrayLike,
    df_sel,
    contrast_col: str = "contrast",
) -> np.ndarray:
    """
    contrast_per_bin[t] = contrast value for each time bin
    Assumes df_sel.loc[cond_idx, contrast_col] exists.
    """
    sel_indices = np.asarray(sel_indices)
    start_bin_global = np.asarray(start_bin_global, dtype=int)
    bins_per_cond = np.asarray(bins_per_cond, dtype=int)

    contrast_per_bin = np.zeros(T, dtype=int)
    for k, cond_idx in enumerate(sel_indices):
        off = int(start_bin_global[k])
        nb = int(bins_per_cond[k])
        contrast_per_bin[off:off+nb] = int(df_sel.loc[cond_idx, contrast_col])
    return contrast_per_bin

def cluster_psth_templates_auto(
    X: ArrayLike,
    tau: ArrayLike,
    cell_cluster: ArrayLike,
    *,
    dt: float = 0.05,
    t_min: float = 0.0,
    t_max: float = 3.0,
    contrast: Optional[int] = None,
    contrast_per_bin: Optional[ArrayLike] = None,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Compute cluster-level PSTH templates (mean spike probability per tau bin).
    X: (T, N) binary (0/1) or rates
    tau: (T,) seconds since onset
    cell_cluster: (N,) cluster labels; may contain NaN / -1

    Returns:
      t: (B,)
      templ: (n_clusters, B) with NaN rows if cluster has no cells
    """
    X = np.asarray(X)
    tau = np.asarray(tau, dtype=float)
    lab = np.asarray(cell_cluster, dtype=float)

    T, N = X.shape
    if tau.shape[0] != T:
        raise ValueError("tau length must match X.shape[0]")

    valid_lab = lab[~np.isnan(lab) & (lab >= 0)]
    if valid_lab.size == 0:
        raise ValueError("No valid cluster labels (non-NaN, >=0)")

    n_clusters = int(valid_lab.max()) + 1

    edges = np.arange(t_min, t_max + dt, dt)
    t = (edges[:-1] + edges[1:]) / 2
    B = len(t)

    bin_id = np.digitize(tau, edges) - 1
    valid_t = (bin_id >= 0) & (bin_id < B)

    if contrast is not None:
        if contrast_per_bin is None:
            raise ValueError("contrast_per_bin is required when contrast is not None")
        contrast_per_bin = np.asarray(contrast_per_bin)
        valid_t &= (contrast_per_bin == int(contrast))

    templ = np.full((n_clusters, B), np.nan)
    b = bin_id[valid_t]

    for cl in range(n_clusters):
        cells = np.where((~np.isnan(lab)) & (lab == cl))[0]
        if len(cells) == 0:
            continue
        y = X[valid_t][:, cells].mean(axis=1)  # (Tv,)
        sums = np.bincount(b, weights=y, minlength=B)
        cnts = np.bincount(b, minlength=B)
        templ[cl] = sums / np.maximum(cnts, 1)

    return t, templ