# -*- coding: utf-8 -*-
"""mode_cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yh1MCqEjCZ0xYAKBVL1lDu8XCDwQtoBy
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, Optional, Tuple

import numpy as np
import pandas as pd

@dataclass(frozen=True)
class ModeClusterResult:
    unique_modes: np.ndarray              # modes that appear in the selected condition
    unique_clusters: np.ndarray           # cluster ids kept in analysis
    mode_cluster_counts: np.ndarray       # shape (len(unique_modes), len(unique_clusters))
    df: pd.DataFrame                      # same as above but as DataFrame
    stim_bins: np.ndarray                 # time bins used for selecting modes


def build_cond_bin_lookup(
    sel_indices: Iterable[int],
    start_bin_global: np.ndarray,
    bins_per_cond: np.ndarray,
) -> Tuple[Dict[int, int], Dict[int, int]]:
    """
    Build mapping from cond_idx -> [start_bin, end_bin) in the raster / modes timeline.
    """
    cond_to_start: Dict[int, int] = {}
    cond_to_end: Dict[int, int] = {}

    for k, cond_idx in enumerate(sel_indices):
        start = int(start_bin_global[k])
        end = int(start_bin_global[k] + bins_per_cond[k])
        cond_to_start[int(cond_idx)] = start
        cond_to_end[int(cond_idx)] = end

    return cond_to_start, cond_to_end

def get_stim_bins_for_condition(
    df_sel: pd.DataFrame,
    cond_to_start: Dict[int, int],
    cond_to_end: Dict[int, int],
    *,
    contrast: float,
    hz: float,
) -> np.ndarray:
    """
    Return all time-bin indices for rows in df_sel matching (contrast, hz).
    Assumes df_sel index is cond_idx (as in your code).
    """
    df_sub = df_sel[(df_sel["contrast"] == float(contrast)) & (df_sel["hz"] == float(hz))]

    stim_bins = []
    for cond_idx in df_sub.index:
        cond_idx = int(cond_idx)
        start = cond_to_start[cond_idx]
        end = cond_to_end[cond_idx]
        stim_bins.extend(range(start, end))

    return np.asarray(stim_bins, dtype=int)

def mode_cluster_counts(
    dominated_mask: np.ndarray,
    cluster_labels: np.ndarray,
    *,
    exclude_noise: bool = True,
    noise_label: int = -1,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Compute full mode x cluster count matrix.
    dominated_mask: (K, Ncells) boolean/int
    cluster_labels: (Ncells,) float or int; may contain NaN for filtered-out cells
    Returns:
      counts: (K, n_clusters)
      unique_clusters: (n_clusters,)
    """
    dominated_mask = np.asarray(dominated_mask)
    if dominated_mask.ndim != 2:
        raise ValueError("dominated_mask must be 2D (K, Ncells)")

    K, N = dominated_mask.shape
    cluster_labels = np.asarray(cluster_labels, dtype=float)

    if len(cluster_labels) < N:
        raise ValueError(
            f"cluster_labels length {len(cluster_labels)} < dominated_mask N {N} (index not aligned)"
        )

    cluster_labels = cluster_labels[:N]

    valid_cell = ~np.isnan(cluster_labels)
    if exclude_noise:
        valid_cell &= (cluster_labels != float(noise_label))

    # keep only clusters that are valid (and usually >=0)
    # If you want to allow negative cluster ids, remove the >=0 constraint
    valid_cell &= (cluster_labels >= 0)

    unique_clusters = np.unique(cluster_labels[valid_cell]).astype(int)
    n_clusters = len(unique_clusters)

    counts = np.zeros((K, n_clusters), dtype=int)
    for j, cl in enumerate(unique_clusters):
        cells_in_cl = valid_cell & (cluster_labels == float(cl))
        counts[:, j] = dominated_mask[:, cells_in_cl].sum(axis=1)

    return counts, unique_clusters

def mode_cluster_for_condition(
    modes: np.ndarray,
    dominated_mask: np.ndarray,
    cluster_labels: np.ndarray,
    df_sel: pd.DataFrame,
    sel_indices: Iterable[int],
    start_bin_global: np.ndarray,
    bins_per_cond: np.ndarray,
    *,
    contrast: float,
    hz: float,
    exclude_noise: bool = True,
    noise_label: int = -1,
) -> ModeClusterResult:
    """
    End-to-end: select stim bins for (contrast, hz), find active modes in those bins,
    then build mode x cluster heatmap counts restricted to those active modes.
    """
    modes = np.asarray(modes, dtype=int)
    if modes.ndim != 1:
        raise ValueError("modes must be 1D (T,)")

    cond_to_start, cond_to_end = build_cond_bin_lookup(sel_indices, start_bin_global, bins_per_cond)
    stim_bins = get_stim_bins_for_condition(df_sel, cond_to_start, cond_to_end, contrast=contrast, hz=hz)

    if stim_bins.size == 0:
        raise ValueError(f"No stim bins found for contrast={contrast}, hz={hz}")

    if stim_bins.min() < 0 or stim_bins.max() >= len(modes):
        raise ValueError("stim_bins out of range for modes length")

    active_modes = np.unique(modes[stim_bins]).astype(int)

    full_counts, unique_clusters = mode_cluster_counts(
        dominated_mask,
        cluster_labels,
        exclude_noise=exclude_noise,
        noise_label=noise_label,
    )

    # restrict to active modes
    counts_active = full_counts[active_modes, :]

    df = pd.DataFrame(
        counts_active,
        index=[f"Mode {m}" for m in active_modes],
        columns=[f"Cluster {c}" for c in unique_clusters],
    )

    return ModeClusterResult(
        unique_modes=active_modes,
        unique_clusters=unique_clusters,
        mode_cluster_counts=counts_active,
        df=df,
        stim_bins=stim_bins,
    )