# -*- coding: utf-8 -*-
"""stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTN8Is_WH8M9S08CI5f0b9OkkIcFf77E
"""

from __future__ import annotations
import numpy as np

try:
    from sklearn.metrics import r2_score as _r2_score
except Exception:
    _r2_score = None


# ============================================================
# Stationary distribution
# ============================================================
def stationary_distribution(A: np.ndarray) -> np.ndarray:
    """Compute stationary distribution w such that w = wA and sum(w)=1."""
    A = np.asarray(A, dtype=float)
    eigvals, eigvecs = np.linalg.eig(A.T)
    idx = int(np.argmin(np.abs(eigvals - 1.0)))
    v = np.real(eigvecs[:, idx])

    w = v / np.sum(v)
    w = np.maximum(w, 0.0)
    w = w / np.sum(w)
    return w


# ============================================================
# Means
# ============================================================
def mean_from_data(X: np.ndarray) -> np.ndarray:
    X = np.asarray(X)
    return X.mean(axis=0)


def mean_from_model(w: np.ndarray, E: np.ndarray) -> np.ndarray:
    return np.asarray(w, float) @ np.asarray(E, float)


# ============================================================
# Covariance (keep your originals)
# ============================================================
def pairwise_cov_from_data(X: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Returns
    -------
    C_data : (N, N) covariance
    m_data : (N,) mean firing prob
    """
    X = np.asarray(X)
    T = X.shape[0]
    m = X.mean(axis=0)            # <σ_i>
    P = (X.T @ X) / T             # <σ_i σ_j>
    C = P - np.outer(m, m)        # cov
    return C, m


def pairwise_cov_from_model(w: np.ndarray, E: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Model (mixture of independent Bernoulli modes):
      m_model = w @ E
      <σ_i σ_j> = sum_a w_a E_ai E_aj
      C = <σ_i σ_j> - m_i m_j
    """
    w = np.asarray(w, dtype=float)
    E = np.asarray(E, dtype=float)

    m_model = w @ E                              # (N,)
    # fast: P_model = E^T diag(w) E = E.T @ (w[:,None] * E)
    P_model = E.T @ (w[:, None] * E)             # (N,N)
    C_model = P_model - np.outer(m_model, m_model)
    return C_model, m_model


def flatten_upper_triangle(C: np.ndarray, k: int = 1) -> np.ndarray:
    C = np.asarray(C, dtype=float)
    iu = np.triu_indices(C.shape[0], k=k)
    return C[iu]


# ============================================================
# Correlation (Prentice Fig.7B uses correlation coefficients)
# ============================================================
def cov_to_corr(C: np.ndarray, m: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    """
    Convert covariance matrix to Pearson correlation matrix for binary σ∈{0,1}.

    Var(σ_i) = m_i (1 - m_i)

    Returns
    -------
    R : (N, N) correlation coefficient matrix
    """
    C = np.asarray(C, dtype=float)
    m = np.asarray(m, dtype=float)

    var = m * (1.0 - m)                           # (N,)
    denom = np.sqrt(np.outer(var, var)) + eps     # (N,N)
    R = C / denom
    np.fill_diagonal(R, 1.0)
    return R


def pairwise_corr_from_data(X: np.ndarray, eps: float = 1e-12) -> tuple[np.ndarray, np.ndarray]:
    """
    Returns
    -------
    R_data : (N, N) correlation coefficients
    m_data : (N,) mean firing prob
    """
    C_data, m_data = pairwise_cov_from_data(X)
    R_data = cov_to_corr(C_data, m_data, eps=eps)
    return R_data, m_data


def pairwise_corr_from_model(w: np.ndarray, E: np.ndarray, eps: float = 1e-12) -> tuple[np.ndarray, np.ndarray]:
    """
    Returns
    -------
    R_model : (N, N) correlation coefficients
    m_model : (N,) model mean firing prob
    """
    C_model, m_model = pairwise_cov_from_model(w, E)
    R_model = cov_to_corr(C_model, m_model, eps=eps)
    return R_model, m_model


def flatten_pairwise_corr(R: np.ndarray) -> np.ndarray:
    """Upper-triangle i<j entries of correlation matrix (Fig.7B-style)."""
    return flatten_upper_triangle(R, k=1)


# ============================================================
# Adaptive binning
# ============================================================
def adaptive_bin_1d(x: np.ndarray, y: np.ndarray, min_bin_size: int = 100):
    """
    Sort by x; split into consecutive bins each with >= min_bin_size points.
    Returns: x_mean, y_mean, x_std, y_std, n_bin
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    if x.shape != y.shape:
        raise ValueError("x and y must have the same shape.")
    if min_bin_size <= 0:
        raise ValueError("min_bin_size must be positive.")

    idx = np.argsort(x)
    x_sorted = x[idx]
    y_sorted = y[idx]

    x_means, y_means, x_stds, y_stds, ns = [], [], [], [], []
    N = len(x_sorted)
    i = 0
    while i < N:
        j = min(i + min_bin_size, N)
        xb = x_sorted[i:j]
        yb = y_sorted[i:j]

        x_means.append(xb.mean())
        y_means.append(yb.mean())
        x_stds.append(xb.std())
        y_stds.append(yb.std())
        ns.append(len(xb))
        i = j

    return (
        np.array(x_means), np.array(y_means),
        np.array(x_stds), np.array(y_stds),
        np.array(ns),
    )


# ============================================================
# Metrics
# ============================================================
def r2_safe(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    if _r2_score is not None:
        return float(_r2_score(x, y))
    ss_res = np.sum((y - x) ** 2)
    ss_tot = np.sum((x - x.mean()) ** 2)
    return float(1.0 - ss_res / (ss_tot + 1e-12))
