# -*- coding: utf-8 -*-
"""transitions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeZy7scp6r1H_2Fmjg2TKA1QGgSvVsMK
"""

from __future__ import annotations
import numpy as np

def off_diagonal_transition(A, eps=1e-12):
    """
    Purpose: remove self-transitions and renormalize each row.
    """
    A = np.asarray(A, dtype=float)
    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError("A must be square (K,K).")

    A_off = A.copy()
    np.fill_diagonal(A_off, 0.0)
    row_sums = A_off.sum(axis=1, keepdims=True)
    A_off = A_off / np.clip(row_sums, eps, None)
    return A_off

def row_entropy(P, eps=1e-12):
    """
    Purpose: per-row Shannon entropy in bits.
    H_i = -sum_j P_ij log2(P_ij)
    """
    P = np.asarray(P, dtype=float)
    if P.ndim != 2:
        raise ValueError("P must be 2D.")
    return -np.sum(P * np.log2(P + eps), axis=1)

def threshold_edges(P, th=0.05, include_self=False):
    """
    Purpose: return (u,v,w) list for edges where P[u,v] > th.
    """
    P = np.asarray(P, dtype=float)
    K = P.shape[0]
    edges = []
    for i in range(K):
        for j in range(K):
            if (not include_self) and (i == j):
                continue
            if P[i, j] > th:
                edges.append((i, j, float(P[i, j])))
    return edges

def mode_occupancy(modes, K):
    """
    Purpose: occupancy w_k = count(k)/T
    """
    modes = np.asarray(modes, dtype=int)
    counts = np.bincount(modes, minlength=K)
    occ = counts / np.maximum(counts.sum(), 1)
    return occ

def chowliu_entropy_rate_all_modes(
    p1_all,
    edges_all,
    pair_probs_all,
    dt,
    eps=1e-12,
):
    """
    Compute Chow–Liu entropy rate (bits/s) for each mode.

    Parameters
    ----------
    p1_all : (K, N) array
        Node marginals p1_all[k,i] = P(x_i=1 | z=k)
    edges_all : list of length K
        edges_all[k] is a list of (i,j) edges for mode k
    pair_probs_all : list of length K
        pair_probs_all[k] is a dict {(i,j): 2x2 joint table}
        table[a,b] = P(x_i=a, x_j=b)
    dt : float
        Time bin size (seconds)
    eps : float
        Numerical epsilon

    Returns
    -------
    S_bits_s : (K,) ndarray
        Entropy rate per mode in bits/s
    """
    p1_all = np.asarray(p1_all, dtype=float)
    K, N = p1_all.shape

    S_bits_bin = np.zeros(K, dtype=float)

    for k in range(K):
        p1 = np.clip(p1_all[k], eps, 1 - eps)

        # 1) Sum of node entropies
        H_nodes = -np.sum(
            p1 * np.log2(p1) + (1 - p1) * np.log2(1 - p1)
        )

        # 2) Subtract mutual information on tree edges
        I_sum = 0.0
        for (i, j) in edges_all[k]:
            # get joint table with correct orientation
            if (i, j) in pair_probs_all[k]:
                P = pair_probs_all[k][(i, j)]
            elif (j, i) in pair_probs_all[k]:
                P = pair_probs_all[k][(j, i)].T
            else:
                raise KeyError(f"Edge ({i},{j}) not found for mode {k}")

            # marginals
            pi1 = p1[i]
            pj1 = p1[j]
            pi0 = 1 - pi1
            pj0 = 1 - pj1

            # mutual information
            for a, pa in enumerate([pi0, pi1]):
                for b, pb in enumerate([pj0, pj1]):
                    pab = P[a, b]
                    if pab > 0:
                        I_sum += pab * np.log2((pab + eps) / (pa * pb + eps))

        S_bits_bin[k] = H_nodes - I_sum

    # convert to bits/s
    return S_bits_bin / dt