# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NADChk66wdoZkoSy5YyEmaLz2gwU8oJl
"""

from __future__ import annotations
import json
import numpy as np
import pandas as pd
import re

# -------------------------
# 1) JSON -> stim dataframe
# -------------------------
def load_stim_json(json_path: str) -> pd.DataFrame:
    with open(json_path) as f:
        con_list = json.load(f)

    stimuli = con_list["stimuli"]

    records = []
    for idx, entry in enumerate(stimuli):

        body = entry.get("bodyMs", 0)
        tail = entry.get("tailMs", 0)

        records.append({
            "stim_index": idx,
            "stimType": entry.get("stimType"),
            "contrast": entry.get("c"),
            "hz": entry.get("hz"),

            # 正确 stimulus duration
            "durationMS": body + tail,
        })

    return pd.DataFrame(records)

def load_spike_txt(path):
    return pd.read_csv(
        path
    )

def load_synctone_csv(csv_path:str) -> pd.DataFrame:
    """
    Load synctone timestamps (seconds).

    Returns
    -------
    DataFrame with columns:
      - stim_index
      - onset_sec
    """

    df = pd.read_csv(csv_path)
    onset_sec = df["Synctone Timestamp (s)"].values.astype(float)

    return pd.DataFrame({
        "stim_index": np.arange(len(onset_sec)),
        "onset_sec": onset_sec})


def build_analysis_windows(
    df_cond: pd.DataFrame,
    df_time: pd.DataFrame | None = None,
    t0: float = 0.0,
    duration_col: str = "durationMS",
    synctone_col: str = "onset_sec",
):

    n_cond = len(df_cond)

    # stimulus duration
    duration_s = df_cond[duration_col].astype(float).to_numpy() / 1000.0

    start_s = np.zeros(n_cond, dtype=float)
    start_s[0] = t0

    # sequential default
    if n_cond > 1:
        start_s[1:] = t0 + np.cumsum(duration_s[:-1])

    # replace by synctone onset
    if df_time is not None and synctone_col in df_time.columns:
        syn_times = df_time[synctone_col].astype(float).to_numpy()

        n_use = min(len(syn_times), n_cond - 1)
        start_s[1:1+n_use] = syn_times[:n_use]

    # correct end
    end_s = start_s + duration_s

    df_out = df_cond.copy()
    df_out["start_s"] = start_s
    df_out["duration_s"] = duration_s
    df_out["end_s"] = end_s

    return df_out

def select_stimulus_segments(
    df_cond: pd.DataFrame,
    selection_strategy: str,
    target_hz: float,
    contrast_levels: list[int] | None = None,
    pair_first=0,
    target_contrast: int | None = None,
    n_rep: int | None = None,
    n_per_rep: int | None = None,
) -> pd.DataFrame:
    """
      Select stimulus segments according to different experimental designs.

      Parameters
      ----------
      df_cond : DataFrame
          Must contain columns: contrast, hz, start_s, end_s
      selection_strategy : str
          One of:
          - "sequential_repetition"
          - "single_condition"
          - "unordered_repetition"
      target_hz : float
          Target temporal frequency (Hz)
      contrast_levels : list[int], optional
          Contrast levels used in repetitions (e.g., [0,50,60,70,80,90])
      target_contrast : int, optional
          Used for single_condition mode
      n_rep : int, optional
          Number of repetitions to keep
      n_per_rep : int, optional
          Number of stimuli per repetition (unordered_repetition)

      Returns
      -------
      DataFrame
          Selected stimulus segments with optional rep_idx column
    """

    # ---------- common preprocessing ----------
    dfc = (
        df_cond
        .dropna(subset=["contrast", "hz"])
        .sort_values(["start_s", "end_s"])
        .reset_index(drop=True)
    )

    # ============================================================
    # Mode 1: sequential repetition (0 -> 50 -> 60 -> ...)
    # ============================================================
    if selection_strategy == "sequential_repetition":
      if contrast_levels is None or n_rep is None:
        raise ValueError("contrast_levels and n_rep must be provided for sequential repetition")

      dfc = dfc.query("hz == @target_hz")

      next_contrast = dfc["contrast"].shift(-1) #get next contrast

      next_hz = dfc["hz"].shift(-1)

      keep = (
          dfc["contrast"].isin(contrast_levels) |
          ((dfc["contrast"]==0)&
           (next_contrast.isin(contrast_levels)) &
           (next_hz == target_hz))
      )

      df_sel = dfc[keep].copy()

      start_rep = (df_sel["contrast"] == 0) & (df_sel["contrast"].shift(-1) == contrast_levels[0])

      df_sel["rep_idx"] = start_rep.cumsum()

      df_sel = df_sel[df_sel["rep_idx"] >= 1]
      df_sel = df_sel[df_sel["rep_idx"] <= n_rep]

      return df_sel.reset_index(drop=True)

     # ============================================================
    # Mode 2: single condition (contrast & hz)
    # ============================================================
    elif selection_strategy == "single_condition":
      if target_contrast is None:
        raise ValueError("target_contrast must be provided for single condition")

      mask_first = (dfc["contrast"] == pair_first) & (dfc["hz"] == target_hz)

      mask_second_next = (
        (dfc["contrast"].shift(-1) == target_contrast) &
        (dfc["hz"].shift(-1) == target_hz)
      )
      # start of a pair: first followed immediately by second
      start_pair = mask_first & mask_second_next

      # select both rows (first + the following second)
      mask_pair = start_pair | start_pair.shift(1).fillna(False)

      df_sel = dfc[mask_pair].copy().reset_index(drop=True)

      # Assign a repetition index (rep_idx) to each pair
      # rep_idx increases by 1 at each occurrence of pair_first
      df_sel["rep_idx"] = (df_sel["contrast"] == pair_first).cumsum()

      # Keep only the first N repetitions
      df_sel = df_sel[df_sel["rep_idx"] <= n_rep].copy().reset_index(drop=True)

      return df_sel


    # ============================================================
    # Mode 3: unordered repetition (fixed block size)
    # ============================================================
    elif selection_strategy == "unordered_repetition":
      if contrast_levels is None or n_rep is None or n_per_rep is None:
            raise ValueError("contrast_levels, n_rep, n_per_rep are required")

      df_sel = dfc[
          (dfc["hz"]==target_hz) &
          (dfc["contrast"].isin(contrast_levels))
      ].copy()

      df_sel["stim_idx"] = np.arange(len(df_sel))

      df_sel["rep_idx"] = (np.arange(len(df_sel)) // n_per_rep) + 1

      df_sel = df_sel[df_sel["rep_idx"] <= n_rep]

      cnt = df_sel.groupby("rep_idx").size()
      good_reps = cnt[cnt==n_per_rep].index
      df_sel = df_sel[df_sel["rep_idx"].isin(cnt[cnt==n_per_rep].index)]

      return df_sel.reset_index(drop=True)

    else:
      raise ValueError(f"Unknown selection strategy: {selection_strategy}")

def split_train_test_by_rep(df_sel: pd.DataFrame, n_train_rep: int):
    """
    Split df_sel into train/test by repetition index (rep_idx).

    Train: rep_idx <= n_train_rep
    Test : rep_idx >  n_train_rep
    """
    if "rep_idx" not in df_sel.columns:
        raise ValueError("df_sel must contain column 'rep_idx'")

    train_df = df_sel[df_sel["rep_idx"] <= n_train_rep].copy().reset_index(drop=True)
    test_df  = df_sel[df_sel["rep_idx"] >  n_train_rep].copy().reset_index(drop=True)
    return train_df, test_df

def make_neuron_index(
    df_spk: pd.DataFrame,
    channel_col: str = "Channel",
    unit_col: str = "Unit",
    neuron_col: str = "Neuron",
    neuron_idx_col: str = "neuron_idx",
) -> tuple[pd.DataFrame, list[tuple], dict[tuple, int]]:
    """
    Create a neuron identifier from (Channel, Unit) and map each neuron to a unique integer index.

    Returns
    -------
    df_spk_out : DataFrame
        Copy of df_spk with added columns:
          - neuron_col (tuple: (Channel, Unit))
          - neuron_idx_col (int: 0..N-1)
    neuron_list : list[tuple]
        Sorted unique neuron identifiers.
    neuron_to_idx : dict[tuple, int]
        Mapping from neuron identifier to integer index.
    """

    df_out = df_spk.copy()

    # Build a stable neuron identifier as a tuple (Channel, Unit)
    df_out[neuron_col] = list(zip(df_out[channel_col], df_out[unit_col]))

    # Sort unique neurons to get a stable mapping across runs
    neuron_list = sorted(df_out[neuron_col].unique())

    # Create a mapping from neuron identifier to integer index
    neuron_to_idx = {n: idx for idx, n in enumerate(neuron_list)}

    # Add integer index
    df_out[neuron_idx_col] = df_out[neuron_col].map(neuron_to_idx).astype(int)

    return df_out, neuron_list, neuron_to_idx

def assign_spikes_to_condition(
    df_spk: pd.DataFrame,
    df_sel: pd.DataFrame,
    time_col: str = "Timestamp",
    start_col: str = "start_s",
    end_col: str = "end_s",
    cond_idx_col: str = "cond_idx",
    default_value: int = -1,
) -> tuple[pd.DataFrame, pd.DataFrame]:

    """
        Assign each spike to a selected stimulus condition based on timestamps.

        A spike belongs to condition i if:
            start_s <= Timestamp < end_s

        Notes
        -----
        - cond_idx values are set to the *row index* from df_sel.iterrows().
          This matches your current notebook logic.

        Returns
        -------
        df_spk_labeled : DataFrame
            Copy of df_spk with added column cond_idx_col.
        df_spk_selected : DataFrame
            Subset of labeled spikes with cond_idx_col >= 0.
    """
    df_out = df_spk.copy()

    # Initialize condition index
    df_out[cond_idx_col] = default_value

    # Iterate through selected conditions and label spikes that fall in each time window
    for cond_idx, row in df_sel.iterrows():
      s = float(row[start_col])
      e = float(row[end_col])
      mask = (df_out[time_col] >= s) & (df_out[time_col] < e)
      df_out.loc[mask, cond_idx_col] = cond_idx

    df_spk_selected = df_out[df_out[cond_idx_col] >= 0].copy() #delete default idx
    return df_out, df_spk_selected

def compute_binning_plan(
    df_sel: pd.DataFrame,
    bin_size_s: float,
    start_col: str = "start_s",
    end_col: str = "end_s",
) -> pd.DataFrame:
    """
    Compute per-condition number of bins and global bin offsets when concatenating conditions.

    For each condition (row) in df_sel:
        duration_s = end_s - start_s
        n_bins = floor(duration_s / bin_size_s)

    Then compute:
        start_bin_global for each condition in the concatenated time axis.

    Returns
    -------
    plan : DataFrame
        Indexed by df_sel.index (same condition indices) with columns:
          - n_bins
          - start_bin_global
          - duration_s
    """

    if bin_size_s <= 0:
        raise ValueError("bin_size_s must be positive")

    sel_indices = df_sel.index.to_list()

    n_bins_list = []
    dur_list = []

    for con_idx in sel_indices:
        row = df_sel.loc[con_idx]
        start_s = row[start_col]
        end_s = row[end_col]
        duration_s = float(end_s) - float(start_s)
        if duration_s <= 0:
            raise ValueError(f"Invalid duration for condition {con_idx}: {duration_s}")

        n_bins = int(np.round(duration_s / bin_size_s))
        n_bins_list.append(n_bins)
        dur_list.append(duration_s)
    n_bins_arr = np.array(n_bins_list)
    start_bin_global = np.cumsum(np.concatenate([[0], n_bins_arr[:-1]]))
    plan = pd.DataFrame(
        {
            "duration_s": dur_list,
            "n_bins": n_bins_arr,
            "start_bin_global": start_bin_global,
        },
        index=sel_indices,
    )
    return plan

def build_binary_matrix(
    df_spk_sel,
    df_sel,
    plan,
    bin_size_s,
    n_neurons,
    time_col="Timestamp",
    neuron_idx_col="neuron_idx",
    cond_idx_col="cond_idx",
    start_col="start_s",
) -> np.ndarray:
    """
    Build a binary spike raster matrix X of shape (N, T).

    X[n, t] = 1 if neuron n fires at least one spike in time bin t.
    """
    total_bins = int(plan["n_bins"].sum())
    X = np.zeros((n_neurons, total_bins), dtype=np.uint8)

    start_s_map = df_sel[start_col].to_dict()
    start_bin_map = plan["start_bin_global"].to_dict()
    n_bins_map = plan["n_bins"].to_dict()

    for _, spk in df_spk_sel.iterrows():
        cond_idx = int(spk[cond_idx_col])
        neuron_idx = int(spk[neuron_idx_col])
        t = float(spk[time_col])

        s0 = float(start_s_map[cond_idx])
        local_bin = int((t - s0) // bin_size_s)

        if local_bin < 0 or local_bin >= int(n_bins_map[cond_idx]):
            continue

        global_bin = int(start_bin_map[cond_idx]) + local_bin
        X[neuron_idx, global_bin] = 1

    return X.T