# -*- coding: utf-8 -*-
"""io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOx-fOo_e1ejdrEfzGBLvfPTArn1wkIx
"""
import numpy as np


def save_state_fps(state_fps, filename):
    np.savez_compressed(filename, state_fps=np.array(state_fps, dtype=object))


def load_state_fps(filename):
    data = np.load(filename, allow_pickle=True)
    return list(data["state_fps"])


def state_list_to_matrix_fp(state_fps):
    """
    Convert a list of per-state fingerprint dicts back to matrix-form fingerprint.

    Supports:
    - base features
    - optional empirical dwell features
    - optional empirical gap features
    - optional empirical visit / occupancy features
    - optional time-profile features
    - optional transition extras
    """
    state_fps = list(state_fps)
    K = len(state_fps)

    if K == 0:
        return {}

    def _arr_scalar(key, default=np.nan, dtype=float):
        return np.array(
            [default if s.get(key, None) is None else s[key] for s in state_fps],
            dtype=dtype
        )

    def _list_array(key, dtype=float):
        return [np.asarray(s.get(key, []), dtype=dtype) for s in state_fps]

    def _stack_vector_feature(key, dtype=float, fill_value=np.nan):
        """
        Stack per-state vector feature into shape (K, D).
        If some states are missing the feature, fill with fill_value.
        """
        first = None
        for s in state_fps:
            if s.get(key, None) is not None:
                first = np.asarray(s[key], dtype=dtype)
                break

        if first is None:
            return None

        dim = len(first)

        out = []
        for s in state_fps:
            if s.get(key, None) is not None:
                out.append(np.asarray(s[key], dtype=dtype))
            else:
                out.append(np.full(dim, fill_value, dtype=dtype))

        return np.stack(out, axis=0)

    fp = {
        "p1": np.stack([np.asarray(s["p1"], float) for s in state_fps], axis=0),

        "edge_set": [s.get("edge_set", None) for s in state_fps],
        "adj": [s.get("adj", None) for s in state_fps],

        "n_edges": _arr_scalar("n_edges", default=np.nan, dtype=float),
        "deg_mean": _arr_scalar("deg_mean", default=np.nan, dtype=float),
        "deg_std": _arr_scalar("deg_std", default=np.nan, dtype=float),

        "Aii": _arr_scalar("Aii", default=np.nan, dtype=float),
        "mean_dwell": _arr_scalar("mean_dwell", default=np.nan, dtype=float),
        "H_off": _arr_scalar("H_off", default=np.nan, dtype=float),
        "occupancy": _arr_scalar("occupancy", default=np.nan, dtype=float),
    }

    # -------------------------
    # Optional empirical visit / occupancy features
    # -------------------------
    if any("occupancy_emp" in s for s in state_fps):
        fp["occupancy_emp"] = _arr_scalar("occupancy_emp", default=np.nan, dtype=float)

    if any("n_visits_emp" in s for s in state_fps):
        fp["n_visits_emp"] = _arr_scalar("n_visits_emp", default=np.nan, dtype=float)

    if any("visit_rate_emp" in s for s in state_fps):
        fp["visit_rate_emp"] = _arr_scalar("visit_rate_emp", default=np.nan, dtype=float)

    # backward compatibility
    if any("n_events_emp" in s for s in state_fps):
        fp["n_events_emp"] = _arr_scalar("n_events_emp", default=np.nan, dtype=float)

    # -------------------------
    # Optional empirical dwell features
    # -------------------------
    if any("dwell_times_emp" in s for s in state_fps):
        fp["dwell_times_emp"] = _list_array("dwell_times_emp", dtype=float)

    if any("mean_dwell_emp" in s for s in state_fps):
        fp["mean_dwell_emp"] = _arr_scalar("mean_dwell_emp", default=np.nan, dtype=float)

    if any("median_dwell_emp" in s for s in state_fps):
        fp["median_dwell_emp"] = _arr_scalar("median_dwell_emp", default=np.nan, dtype=float)

    if any("std_dwell_emp" in s for s in state_fps):
        fp["std_dwell_emp"] = _arr_scalar("std_dwell_emp", default=np.nan, dtype=float)

    if any("cv_dwell_emp" in s for s in state_fps):
        fp["cv_dwell_emp"] = _arr_scalar("cv_dwell_emp", default=np.nan, dtype=float)

    if any("n_dwell_emp" in s for s in state_fps):
        fp["n_dwell_emp"] = _arr_scalar("n_dwell_emp", default=np.nan, dtype=float)

    if any("dwell_quantiles_emp" in s for s in state_fps):
        fp["dwell_quantiles_emp"] = _stack_vector_feature(
            "dwell_quantiles_emp", dtype=float, fill_value=np.nan
        )

    # -------------------------
    # Optional empirical gap features
    # -------------------------
    if any("gap_times_emp" in s for s in state_fps):
        fp["gap_times_emp"] = _list_array("gap_times_emp", dtype=float)

    if any("mean_gap_emp" in s for s in state_fps):
        fp["mean_gap_emp"] = _arr_scalar("mean_gap_emp", default=np.nan, dtype=float)

    if any("median_gap_emp" in s for s in state_fps):
        fp["median_gap_emp"] = _arr_scalar("median_gap_emp", default=np.nan, dtype=float)

    if any("std_gap_emp" in s for s in state_fps):
        fp["std_gap_emp"] = _arr_scalar("std_gap_emp", default=np.nan, dtype=float)

    if any("cv_gap_emp" in s for s in state_fps):
        fp["cv_gap_emp"] = _arr_scalar("cv_gap_emp", default=np.nan, dtype=float)

    if any("n_gap_emp" in s for s in state_fps):
        fp["n_gap_emp"] = _arr_scalar("n_gap_emp", default=np.nan, dtype=float)

    if any("gap_quantiles_emp" in s for s in state_fps):
        fp["gap_quantiles_emp"] = _stack_vector_feature(
            "gap_quantiles_emp", dtype=float, fill_value=np.nan
        )

    # -------------------------
    # Optional time-profile features
    # -------------------------
    if any("time_profile_emp" in s for s in state_fps):
        fp["time_profile_emp"] = _stack_vector_feature(
            "time_profile_emp", dtype=float, fill_value=np.nan
        )

    if any("time_profile_shape_emp" in s for s in state_fps):
        fp["time_profile_shape_emp"] = _stack_vector_feature(
            "time_profile_shape_emp", dtype=float, fill_value=np.nan
        )

    # -------------------------
    # Optional transition extras
    # -------------------------
    if any("A_row" in s for s in state_fps):
        fp["A"] = np.stack([
            np.asarray(s["A_row"], float)
            if s.get("A_row", None) is not None
            else np.full(K, np.nan, dtype=float)
            for s in state_fps
        ], axis=0)

    if any("pi" in s for s in state_fps):
        fp["pi"] = _arr_scalar("pi", default=np.nan, dtype=float)

    return fp


def summarize_fp(fp, name="fp"):
    K, N = fp["p1"].shape
    print(f"\n=== {name} ===")
    print(f"K={K}, N={N}")
    print(f"p1 min/max: {np.nanmin(fp['p1']):.4f} / {np.nanmax(fp['p1']):.4f}")
    print(f"occupancy sum: {fp['occupancy'].sum():.6f}")

    for k in [
        "occupancy_emp",
        "n_visits_emp",
        "visit_rate_emp",
        "mean_dwell_emp",
        "cv_dwell_emp",
        "mean_gap_emp",
        "cv_gap_emp",
        "time_profile_emp",
        "time_profile_shape_emp",
    ]:
        if k in fp:
            v = fp[k]
            shape = getattr(v, "shape", None)
            print(f"{k}: present, shape={shape}")
        else:
            print(f"{k}: missing")