# -*- coding: utf-8 -*-
"""overview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtqgO2lhl5DJOUEHUagZhSRL-Zjg7sPZ
"""
import os
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from .matching import (
    summarize_retina_matching_true_bidirectional,
)




def _pick_evenly_spaced_reps(n_rep, max_reps=4):
    if n_rep <= max_reps:
        return list(range(n_rep))
    return np.linspace(0, n_rep - 1, max_reps, dtype=int).tolist()


def _plot_state_small_on_ax(
    ax,
    z_reps,
    keep_state,
    title="",
    bin_ms=10,
    reps_keep=None,
    max_reps=4,
    time_window=None,
):
    Z = np.asarray(z_reps)

    if reps_keep is None:
        reps_keep = _pick_evenly_spaced_reps(Z.shape[0], max_reps=max_reps)

    Zs = Z[reps_keep]
    mask = (Zs == int(keep_state)).astype(int)

    if time_window is not None:
        t0, t1 = time_window
        i0 = max(0, int(round(t0 * 1000 / bin_ms)))
        i1 = min(mask.shape[1], int(round(t1 * 1000 / bin_ms)))
        mask = mask[:, i0:i1]
        x0, x1 = t0, t1
    else:
        x0 = 0.0
        x1 = mask.shape[1] * bin_ms / 1000.0

    cmap = ListedColormap(["#cfcfcf", "#e69f00"])

    ax.imshow(
        mask,
        aspect="auto",
        interpolation="nearest",
        cmap=cmap,
        vmin=0,
        vmax=1,
        origin="upper",
    )

    ax.set_title(title, fontsize=9, pad=2)

    nT = mask.shape[1]
    if nT > 1:
        xt = np.linspace(0, nT - 1, 4, dtype=int)
        xl = np.linspace(x0, x1, 4)
        ax.set_xticks(xt)
        ax.set_xticklabels([f"{v:.0f}" for v in xl], fontsize=7)
    else:
        ax.set_xticks([])

    ax.set_yticks(range(len(reps_keep)))
    ax.set_yticklabels([f"r{r+1}" for r in reps_keep], fontsize=7)

    for spine in ax.spines.values():
        spine.set_linewidth(0.6)


def make_true_bidirectional_matching_overview_figure(
    df_AB,
    df_BA,
    sim_AB,
    sim_BA,
    sim_sym,
    z_repsA,
    z_repsB,
    top_n=4,
    bin_ms=10,
    time_window=None,
    max_reps=4,
    figsize=(18, 12),
    savepath=None,
):
    """
    Overview figure aligned with summarize_retina_matching_true_bidirectional().

    Expected columns in df_AB / df_BA:
        A_state, B_state,
        match_dist, dist_norm_global, dist_sim_global, pair_score,
        A_occ, B_occ, pair_weight
    """
    df_AB = df_AB.copy()
    df_BA = df_BA.copy()

    # -------------------------
    # matched / unmatched split
    # -------------------------
    matched_AB_full = df_AB[
        df_AB["A_state"].notna() & df_AB["B_state"].notna()
    ].copy()

    matched_BA_full = df_BA[
        df_BA["A_state"].notna() & df_BA["B_state"].notna()
    ].copy()

    if len(matched_AB_full):
        matched_AB_full["A_state"] = matched_AB_full["A_state"].astype(int)
        matched_AB_full["B_state"] = matched_AB_full["B_state"].astype(int)

    if len(matched_BA_full):
        matched_BA_full["A_state"] = matched_BA_full["A_state"].astype(int)
        matched_BA_full["B_state"] = matched_BA_full["B_state"].astype(int)

    unmatched_A = df_AB[
        df_AB["A_state"].notna() & df_AB["B_state"].isna()
    ].copy()

    unmatched_B = df_BA[
        df_BA["A_state"].isna() & df_BA["B_state"].notna()
    ].copy()

    if len(unmatched_A):
        unmatched_A["A_state"] = unmatched_A["A_state"].astype(int)

    if len(unmatched_B):
        unmatched_B["B_state"] = unmatched_B["B_state"].astype(int)

    # -------------------------
    # choose rows to display
    # -------------------------
    matched_AB = matched_AB_full.sort_values(
        ["A_occ", "pair_score"], ascending=False
    ).head(top_n)

    matched_BA = matched_BA_full.sort_values(
        ["B_occ", "pair_score"], ascending=False
    ).head(top_n)

    # -------------------------
    # canvas
    # -------------------------
    fig = plt.figure(figsize=figsize)
    gs = fig.add_gridspec(
        nrows=top_n + 2,
        ncols=4,
        height_ratios=[1] * top_n + [0.8, 1.2],
        hspace=0.85,
        wspace=0.4,
    )

    fig.suptitle(
        "True Bidirectional Retina State Matching Overview",
        fontsize=16,
        y=0.995,
    )
    fig.text(0.25, 0.965, "A → B (top rows by A occupancy)", ha="center", fontsize=12)
    fig.text(0.75, 0.965, "B → A (top rows by B occupancy)", ha="center", fontsize=12)

    # -------------------------
    # top matched rows
    # -------------------------
    for i in range(top_n):
        # left half: A -> B
        axA = fig.add_subplot(gs[i, 0])
        axB = fig.add_subplot(gs[i, 1])

        if i < len(matched_AB):
            row = matched_AB.iloc[i]
            a_idx = int(row["A_state"])
            b_idx = int(row["B_state"])

            _plot_state_small_on_ax(
                axA,
                z_repsA,
                a_idx,
                title=f"A s{a_idx} | occ={row['A_occ']:.2f}",
                bin_ms=bin_ms,
                max_reps=max_reps,
                time_window=time_window,
            )
            _plot_state_small_on_ax(
                axB,
                z_repsB,
                b_idx,
                title=f"B s{b_idx} | sim={row['pair_score']:.2f}",
                bin_ms=bin_ms,
                max_reps=max_reps,
                time_window=time_window,
            )
        else:
            axA.axis("off")
            axB.axis("off")

        # right half: B -> A
        axB2 = fig.add_subplot(gs[i, 2])
        axA2 = fig.add_subplot(gs[i, 3])

        if i < len(matched_BA):
            row = matched_BA.iloc[i]
            a_idx = int(row["A_state"])
            b_idx = int(row["B_state"])

            _plot_state_small_on_ax(
                axB2,
                z_repsB,
                b_idx,
                title=f"B s{b_idx} | occ={row['B_occ']:.2f}",
                bin_ms=bin_ms,
                max_reps=max_reps,
                time_window=time_window,
            )
            _plot_state_small_on_ax(
                axA2,
                z_repsA,
                a_idx,
                title=f"A s{a_idx} | sim={row['pair_score']:.2f}",
                bin_ms=bin_ms,
                max_reps=max_reps,
                time_window=time_window,
            )
        else:
            axB2.axis("off")
            axA2.axis("off")

    # -------------------------
    # unmatched text blocks
    # -------------------------
    ax_unA = fig.add_subplot(gs[top_n, 0:2])
    ax_unB = fig.add_subplot(gs[top_n, 2:4])

    ax_unA.axis("off")
    ax_unB.axis("off")

    if len(unmatched_A) == 0:
        txtA = "Unmatched A: none"
    else:
        lines = ["Unmatched A:"]
        unmatched_A_show = unmatched_A.sort_values("A_occ", ascending=False)
        for _, row in unmatched_A_show.iterrows():
            a_idx = int(row["A_state"])
            occ = float(row["A_occ"]) if pd.notna(row["A_occ"]) else np.nan
            lines.append(f"  A s{a_idx}  (occ={occ:.3f})")
        txtA = "\n".join(lines)

    if len(unmatched_B) == 0:
        txtB = "Unmatched B: none"
    else:
        lines = ["Unmatched B:"]
        unmatched_B_show = unmatched_B.sort_values("B_occ", ascending=False)
        for _, row in unmatched_B_show.iterrows():
            b_idx = int(row["B_state"])
            occ = float(row["B_occ"]) if pd.notna(row["B_occ"]) else np.nan
            lines.append(f"  B s{b_idx}  (occ={occ:.3f})")
        txtB = "\n".join(lines)

    ax_unA.text(0.0, 1.0, txtA, va="top", fontsize=10)
    ax_unB.text(0.0, 1.0, txtB, va="top", fontsize=10)

    # -------------------------
    # table block
    # -------------------------
    ax_tab = fig.add_subplot(gs[top_n + 1, 0:2])
    ax_tab.axis("off")

    tab_AB = matched_AB_full.copy()
    tab_BA = matched_BA_full.copy()

    if len(tab_AB):
        tab_AB["seen_in"] = "A→B"

    if len(tab_BA):
        tab_BA["seen_in"] = "B→A"

    tab_union = pd.concat([tab_AB, tab_BA], axis=0, ignore_index=True)

    if len(tab_union):
        tab_union["A_state"] = tab_union["A_state"].astype(int)
        tab_union["B_state"] = tab_union["B_state"].astype(int)

        agg_dict = {
            "seen_in": lambda s: "/".join(sorted(set(s))),
            "match_dist": "min",
            "dist_norm_global": "max",
            "dist_sim_global": "max",
            "pair_score": "max",
            "A_occ": "max",
            "B_occ": "max",
            "pair_weight": "max",
        }

        tab = (
            tab_union.groupby(["A_state", "B_state"], as_index=False)
            .agg(agg_dict)
            .sort_values(["pair_score", "pair_weight"], ascending=False)
            .head(8)
        )

        tab["A_state"] = tab["A_state"].map(lambda x: f"A s{int(x)}")
        tab["B_state"] = tab["B_state"].map(lambda x: f"B s{int(x)}")

        for col in [
            "match_dist",
            "dist_norm_global",
            "dist_sim_global",
            "pair_score",
            "A_occ",
            "B_occ",
            "pair_weight",
        ]:
            tab[col] = tab[col].map(lambda x: f"{x:.3f}")

        tab = tab.rename(
            columns={
                "seen_in": "seen_in",
                "A_state": "A state",
                "B_state": "B state",
                "match_dist": "dist",
                "dist_norm_global": "dist_norm",
                "dist_sim_global": "dist_sim",
                "pair_score": "pair_score",
                "A_occ": "A_occ",
                "B_occ": "B_occ",
                "pair_weight": "weight",
            }
        )

        table = ax_tab.table(
            cellText=tab.values,
            colLabels=tab.columns,
            loc="center",
            cellLoc="center",
        )
        table.auto_set_font_size(False)
        table.set_fontsize(8)
        table.scale(1.0, 1.3)
    else:
        ax_tab.text(0.0, 0.5, "No matched pairs to summarize.", fontsize=10)

    ax_tab.set_title("Pair metrics (union of A→B and B→A)", fontsize=11, pad=8)

    # -------------------------
    # summary block
    # -------------------------
    ax_sum = fig.add_subplot(gs[top_n + 1, 2:4])
    ax_sum.axis("off")

    sim_quality_sym = 0.5 * (
        sim_AB["matched_pair_score"] + sim_BA["matched_pair_score"]
    )

    summary_txt = (
        "Summary\n"
        "-------\n"
        f"A→B matched quality: {sim_AB['matched_pair_score']:.3f}\n"
        f"A→B coverage:        {sim_AB['coverage']:.3f}\n"
        f"A→B overall:         {sim_AB['overall_similarity']:.3f}\n\n"
        f"B→A matched quality: {sim_BA['matched_pair_score']:.3f}\n"
        f"B→A coverage:        {sim_BA['coverage']:.3f}\n"
        f"B→A overall:         {sim_BA['overall_similarity']:.3f}\n\n"
        f"Symmetric quality:   {sim_quality_sym:.3f}\n"
        f"Symmetric similarity:{sim_sym:.3f}\n"
        f"Symmetric %:         {100 * sim_sym:.1f}%"
    )

    ax_sum.text(
        0.0,
        1.0,
        summary_txt,
        va="top",
        ha="left",
        fontsize=13,
        family="monospace",
    )

    plt.tight_layout(rect=[0, 0, 1, 0.97])

    if savepath is not None:
        fig.savefig(savepath, dpi=200, bbox_inches="tight")

    return fig


def save_single_state_panel(
    z_reps,
    state,
    title,
    savepath,
    bin_ms=10,
    max_reps=4,
    time_window=None,
    figsize=(6, 2.6),
):
    fig, ax = plt.subplots(figsize=figsize)
    _plot_state_small_on_ax(
        ax=ax,
        z_reps=z_reps,
        keep_state=state,
        title=title,
        bin_ms=bin_ms,
        max_reps=max_reps,
        time_window=time_window,
    )
    fig.tight_layout()
    fig.savefig(savepath, dpi=200, bbox_inches="tight")
    plt.close(fig)

def save_matched_pair_figure(
    a_state,
    b_state,
    row,
    z_repsA,
    z_repsB,
    savepath,
    bin_ms=10,
    max_reps=4,
    time_window=None,
    figsize=(10, 3.2),
):
    fig, axes = plt.subplots(1, 2, figsize=figsize)

    _plot_state_small_on_ax(
        axes[0],
        z_repsA,
        a_state,
        title=f"A s{a_state} | occ={row['A_occ']:.3f}",
        bin_ms=bin_ms,
        max_reps=max_reps,
        time_window=time_window,
    )
    _plot_state_small_on_ax(
        axes[1],
        z_repsB,
        b_state,
        title=f"B s{b_state} | sim={row['pair_score']:.3f}",
        bin_ms=bin_ms,
        max_reps=max_reps,
        time_window=time_window,
    )

    fig.suptitle(
        f"A s{a_state} ↔ B s{b_state} | "
        f"dist={row['match_dist']:.3f}, sim={row['pair_score']:.3f}",
        fontsize=12,
        y=1.02,
    )
    fig.tight_layout()
    fig.savefig(savepath, dpi=200, bbox_inches="tight")
    plt.close(fig)

def save_unmatched_state_figure(
    state,
    side,
    occ,
    z_reps,
    savepath,
    bin_ms=10,
    max_reps=4,
    time_window=None,
    figsize=(6, 2.6),
):
    fig, ax = plt.subplots(figsize=figsize)
    _plot_state_small_on_ax(
        ax,
        z_reps,
        state,
        title=f"{side} s{state} (UNMATCHED) | occ={occ:.3f}",
        bin_ms=bin_ms,
        max_reps=max_reps,
        time_window=time_window,
    )
    fig.tight_layout()
    fig.savefig(savepath, dpi=200, bbox_inches="tight")
    plt.close(fig)


def export_one_pair_results(
    key,
    distance_dict,
    pair_inputs,
    tau,
    global_dmin,
    global_dmax,
    base_dir="/content/drive/MyDrive/upstate/mode_project/matching_results",
    top_n_overview=4,
    bin_ms=10,
    max_reps=4,
    time_window=None,
    allow_many_to_one=True,
):
    nameA, nameB = key
    pair_name = f"{nameA}__vs__{nameB}"

    pair_dir = Path(base_dir) / pair_name
    matched_dir = pair_dir / "matched_pairs"
    unmatched_A_dir = pair_dir / "unmatched_A"
    unmatched_B_dir = pair_dir / "unmatched_B"
    overview_dir = pair_dir / "overview"
    tables_dir = pair_dir / "tables"

    for d in [pair_dir, matched_dir, unmatched_A_dir, unmatched_B_dir, overview_dir, tables_dir]:
        d.mkdir(parents=True, exist_ok=True)

    D = distance_dict[key]
    info = pair_inputs[key]

    # -------- run bidirectional summary --------
    df_AB, df_BA, sim_AB, sim_BA, sim_sym, outs = summarize_retina_matching_true_bidirectional(
        D=D,
        fpA=info["fpA"],
        fpB=info["fpB"],
        tau=tau,
        global_dmin=global_dmin,
        global_dmax=global_dmax,
        pairs_AB=info["pairs_AB"],
        pairs_BA=info["pairs_BA"],
        z_repsA=info["z_repsA"],
        z_repsB=info["z_repsB"],
        allow_many_to_one=allow_many_to_one,
        do_plot=False,   # 这里关掉，不然 notebook 里会爆很多图
    )

    # -------- save overview figure --------
    overview_path = overview_dir / f"{pair_name}_overview.png"
    fig = make_true_bidirectional_matching_overview_figure(
        df_AB=df_AB,
        df_BA=df_BA,
        sim_AB=sim_AB,
        sim_BA=sim_BA,
        sim_sym=sim_sym,
        z_repsA=info["z_repsA"],
        z_repsB=info["z_repsB"],
        top_n=top_n_overview,
        bin_ms=bin_ms,
        time_window=time_window,
        max_reps=max_reps,
        figsize=(18, 12),
        savepath=str(overview_path),
    )
    plt.close(fig)

    # -------- save tables --------
    df_AB.to_csv(tables_dir / f"{pair_name}_A_to_B.csv", index=False)
    df_BA.to_csv(tables_dir / f"{pair_name}_B_to_A.csv", index=False)

    summary_df = pd.DataFrame([{
        "pair": pair_name,
        "tau": tau,
        "global_dmin": global_dmin,
        "global_dmax": global_dmax,
        "A_to_B_matched_quality": sim_AB["matched_pair_score"],
        "A_to_B_coverage": sim_AB["coverage"],
        "A_to_B_overall_similarity": sim_AB["overall_similarity"],
        "B_to_A_matched_quality": sim_BA["matched_pair_score"],
        "B_to_A_coverage": sim_BA["coverage"],
        "B_to_A_overall_similarity": sim_BA["overall_similarity"],
        "symmetric_similarity": sim_sym,
        "method_AB": outs["AB"]["method"],
        "method_BA": outs["BA"]["method"],
    }])
    summary_df.to_csv(tables_dir / f"{pair_name}_summary.csv", index=False)

    with open(tables_dir / f"{pair_name}_summary.txt", "w") as f:
        f.write(f"pair: {pair_name}\n")
        f.write(f"tau: {tau:.6f}\n")
        f.write(f"global_dmin: {global_dmin:.6f}\n")
        f.write(f"global_dmax: {global_dmax:.6f}\n\n")

        f.write("[A -> B]\n")
        f.write(f"matched_pair_score: {sim_AB['matched_pair_score']:.6f}\n")
        f.write(f"coverage: {sim_AB['coverage']:.6f}\n")
        f.write(f"overall_similarity: {sim_AB['overall_similarity']:.6f}\n\n")

        f.write("[B -> A]\n")
        f.write(f"matched_pair_score: {sim_BA['matched_pair_score']:.6f}\n")
        f.write(f"coverage: {sim_BA['coverage']:.6f}\n")
        f.write(f"overall_similarity: {sim_BA['overall_similarity']:.6f}\n\n")

        f.write("[Symmetric]\n")
        f.write(f"symmetric_similarity: {sim_sym:.6f}\n\n")

        f.write("[Methods]\n")
        f.write(f"AB method: {outs['AB']['method']}\n")
        f.write(f"BA method: {outs['BA']['method']}\n")
        f.write(f"AB diag: {outs['AB']['diag']}\n")
        f.write(f"BA diag: {outs['BA']['diag']}\n")

    # -------- matched pairs: use union of AB and BA --------
    matched_AB_full = df_AB[df_AB["A_state"].notna() & df_AB["B_state"].notna()].copy()
    matched_BA_full = df_BA[df_BA["A_state"].notna() & df_BA["B_state"].notna()].copy()

    if len(matched_AB_full):
        matched_AB_full["A_state"] = matched_AB_full["A_state"].astype(int)
        matched_AB_full["B_state"] = matched_AB_full["B_state"].astype(int)
        matched_AB_full["seen_in"] = "AtoB"

    if len(matched_BA_full):
        matched_BA_full["A_state"] = matched_BA_full["A_state"].astype(int)
        matched_BA_full["B_state"] = matched_BA_full["B_state"].astype(int)
        matched_BA_full["seen_in"] = "BtoA"

    tab_union = pd.concat([matched_AB_full, matched_BA_full], axis=0, ignore_index=True)

    if len(tab_union):
        tab_union = (
            tab_union.groupby(["A_state", "B_state"], as_index=False)
            .agg({
                "seen_in": lambda s: "/".join(sorted(set(s))),
                "match_dist": "min",
                "dist_norm_global": "max",
                "dist_sim_global": "max",
                "pair_score": "max",
                "A_occ": "max",
                "B_occ": "max",
                "pair_weight": "max",
            })
            .sort_values(["pair_score", "pair_weight"], ascending=False)
        )

        tab_union.to_csv(tables_dir / f"{pair_name}_matched_union.csv", index=False)

        for _, row in tab_union.iterrows():
            a_state = int(row["A_state"])
            b_state = int(row["B_state"])
            seen_in = str(row["seen_in"]).replace("/", "-")

            savepath = matched_dir / (
                f"A_s{a_state:02d}__B_s{b_state:02d}__"
                f"sim_{row['pair_score']:.3f}__{seen_in}.png"
            )

            save_matched_pair_figure(
                a_state=a_state,
                b_state=b_state,
                row=row,
                z_repsA=info["z_repsA"],
                z_repsB=info["z_repsB"],
                savepath=str(savepath),
                bin_ms=bin_ms,
                max_reps=max_reps,
                time_window=time_window,
            )

    # -------- unmatched A --------
    unmatched_A = df_AB[df_AB["A_state"].notna() & df_AB["B_state"].isna()].copy()
    if len(unmatched_A):
        unmatched_A["A_state"] = unmatched_A["A_state"].astype(int)
        unmatched_A = unmatched_A.sort_values("A_occ", ascending=False)
        unmatched_A.to_csv(tables_dir / f"{pair_name}_unmatched_A.csv", index=False)

        for _, row in unmatched_A.iterrows():
            a_state = int(row["A_state"])
            occ = float(row["A_occ"])
            savepath = unmatched_A_dir / f"A_s{a_state:02d}__occ_{occ:.3f}.png"
            save_unmatched_state_figure(
                state=a_state,
                side="A",
                occ=occ,
                z_reps=info["z_repsA"],
                savepath=str(savepath),
                bin_ms=bin_ms,
                max_reps=max_reps,
                time_window=time_window,
            )

    # -------- unmatched B --------
    unmatched_B = df_BA[df_BA["A_state"].isna() & df_BA["B_state"].notna()].copy()
    if len(unmatched_B):
        unmatched_B["B_state"] = unmatched_B["B_state"].astype(int)
        unmatched_B = unmatched_B.sort_values("B_occ", ascending=False)
        unmatched_B.to_csv(tables_dir / f"{pair_name}_unmatched_B.csv", index=False)

        for _, row in unmatched_B.iterrows():
            b_state = int(row["B_state"])
            occ = float(row["B_occ"])
            savepath = unmatched_B_dir / f"B_s{b_state:02d}__occ_{occ:.3f}.png"
            save_unmatched_state_figure(
                state=b_state,
                side="B",
                occ=occ,
                z_reps=info["z_repsB"],
                savepath=str(savepath),
                bin_ms=bin_ms,
                max_reps=max_reps,
                time_window=time_window,
            )

    print(f"Saved pair results to: {pair_dir}")
    return {
        "pair_dir": str(pair_dir),
        "df_AB": df_AB,
        "df_BA": df_BA,
        "sim_AB": sim_AB,
        "sim_BA": sim_BA,
        "sim_sym": sim_sym,
        "outs": outs,
    }