# -*- coding: utf-8 -*-
"""plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQyQ87N6nLxiDx3Cg9M6SOHCHpeMPzN-
"""

import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Patch

COLORBLIND_PALETTE = [
    "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
    "#000000", "#999999", "#882255", "#AA4499", "#117733", "#44AA99", "#DDCC77",
    "#88CCEE", "#332288", "#661100", "#6699CC", "#AA4455", "#228833", "#CCBB44",
    "#EE6677", "#AA7744", "#774411", "#114477", "#771155", "#555555", "#99DDFF",
    "#77AADD", "#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02",
    "#A6761D", "#666666", "#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854",
    "#FFD92F", "#E5C494", "#B3B3B3",
]


def segments_from_states(z):
    z = np.asarray(z).astype(int)
    if len(z) == 0:
        return []

    segs = []
    start = 0
    cur = z[0]
    for t in range(1, len(z)):
        if z[t] != cur:
            segs.append((start, t, cur))
            start = t
            cur = z[t]
    segs.append((start, len(z), cur))
    return segs


def remap_states_keep(z_reps, keep_states, other_state=-1):
    keep = set(map(int, keep_states))
    Z = np.asarray(z_reps).astype(int).copy()
    Z[~np.isin(Z, list(keep))] = int(other_state)
    return Z

def plot_viterbi_bands_reps(
    z_reps,
    bin_ms=None,
    title="Viterbi segmentation across reps",
    rep_labels=None,
    figsize=None,
    show_legend=True,
    legend_top_n=None,     # 只显示出现最多的前N个state（OTHER 会自动保留）
    other_state=-1,        # OTHER 的 state id
    other_color=(0.85, 0.85, 0.85),  # OTHER 的颜色
):
    """
    z_reps: (n_reps, T_rep) int array
    """
    Z = np.asarray(z_reps).astype(int)
    assert Z.ndim == 2, "z_reps must be 2D: (n_reps, T_rep)"
    n_reps, T = Z.shape

    # x-axis
    if bin_ms is None:
        to_x = lambda t: t
        xlabel = "time bin"
        x_end = T
    else:
        to_x = lambda t: t * (bin_ms / 1000.0)
        xlabel = "time (s)"
        x_end = to_x(T)

    # states and counts
    all_states = np.unique(Z)
    state_counts = {s: int(np.sum(Z == s)) for s in all_states}
    sorted_states = sorted(all_states, key=lambda s: state_counts[s], reverse=True)

    # restrict legend (but keep OTHER)
    if legend_top_n is not None:
        top = list(sorted_states[:legend_top_n])
        if other_state in all_states and other_state not in top:
            top.append(other_state)
        sorted_states = top

    # put OTHER at the end if present
    if other_state in sorted_states:
        sorted_states = [s for s in sorted_states if s != other_state] + [other_state]

    # color mapping
    palette = COLORBLIND_PALETTE
    n_palette = len(palette)
    state_to_color = {}
    pi = 0
    for s in sorted_states:
        if s == other_state:
            state_to_color[s] = other_color
        else:
            state_to_color[s] = palette[pi % n_palette]
            pi += 1

    # labels / figsize
    if rep_labels is None:
        rep_labels = [f"rep {i+1}" for i in range(n_reps)]
    if figsize is None:
        figsize = (14, max(2.5, 0.55 * n_reps))

    fig, ax = plt.subplots(figsize=figsize)

    band_h = 0.8
    gap = 0.25

    # draw bands
    for r in range(n_reps):
        z = Z[r]
        segs = segments_from_states(z)
        y0 = (n_reps - 1 - r) * (band_h + gap)

        for (a, b, s) in segs:
            if s not in state_to_color:
                continue
            xa, xb = to_x(a), to_x(b)
            ax.add_patch(Rectangle(
                (xa, y0), xb - xa, band_h,
                linewidth=0,
                facecolor=state_to_color[s]
            ))

    ax.set_xlim(0, x_end)
    ax.set_ylim(-gap, n_reps * (band_h + gap))
    ax.set_xlabel(xlabel)
    ax.set_title(title)

    yticks = [(n_reps - 1 - r) * (band_h + gap) + band_h / 2 for r in range(n_reps)]
    ax.set_yticks(yticks)
    ax.set_yticklabels(rep_labels)

    ax.grid(True, axis="x", alpha=0.3)

    # legend
    if show_legend:
        handles = [
            Patch(
                facecolor=state_to_color[s],
                label=("OTHER" if s == other_state else f"State {s}")
            )
            for s in sorted_states
        ]

        max_rows = 16
        n_items = len(handles)
        ncol = max(1, math.ceil(n_items / max_rows))

        # reserve space on right
        fig.subplots_adjust(right=0.78)

        ax.legend(
            handles=handles,
            ncol=ncol,
            bbox_to_anchor=(1.02, 1),
            loc="upper left",
            borderaxespad=0.,
            columnspacing=1.0,
            handlelength=1.2,
            handletextpad=0.4,
            fontsize=9,
            frameon=True
        )

    plt.tight_layout()
    plt.show()