# -*- coding: utf-8 -*-
"""discriminability_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMH8l7cPE5aCCP-qKv1j1OZhnkJrmBP7
"""

from __future__ import annotations

from typing import Optional, Tuple

import numpy as np
import matplotlib.pyplot as plt

from ..discriminability import split_modes, lda_projection_1d

def plot_mode_raster(
    X,
    modes,
    alpha: int,
    *,
    ax: Optional[plt.Axes] = None,
    cmap: str = "Greys",
    title: Optional[str] = None,
) -> plt.Axes:
    Xa, _ = split_modes(X, modes, alpha, alpha)  # hack to reuse split; beta==alpha gives same
    if ax is None:
        fig, ax = plt.subplots()
    ax.imshow(Xa, aspect="auto", cmap=cmap)
    ax.set_title(title or f"Mode {alpha}")
    ax.set_xlabel("features")
    ax.set_ylabel("samples")
    return ax

def plot_two_modes_raster(
    X,
    modes,
    alpha: int,
    beta: int,
    *,
    cmap_alpha: str = "Greys",
    cmap_beta: str = "Reds",
) -> Tuple[plt.Figure, np.ndarray]:
    Xa, Xb = split_modes(X, modes, alpha, beta)
    fig, axes = plt.subplots(2, 1, figsize=(8, 6), sharex=True)

    axes[0].imshow(Xa, aspect="auto", cmap=cmap_alpha)
    axes[0].set_title(f"Mode {alpha}")

    axes[1].imshow(Xb, aspect="auto", cmap=cmap_beta)
    axes[1].set_title(f"Mode {beta}")

    axes[1].set_xlabel("features")
    for ax in axes:
        ax.set_ylabel("samples")
    fig.tight_layout()
    return fig, axes

def plot_lda_kde(
    X,
    modes,
    alpha: int,
    beta: int,
    *,
    bins: int = 60,
) -> plt.Axes:
    """
    Pure-matplotlib density plot (avoid seaborn dependency).
    """
    Xa, Xb = split_modes(X, modes, alpha, beta)
    Za, Zb, _ = lda_projection_1d(Xa, Xb)

    fig, ax = plt.subplots(figsize=(7, 4))
    allz = np.concatenate([Za, Zb])
    lo, hi = np.percentile(allz, [1, 99])
    xs = np.linspace(lo, hi, 300)

    # simple histogram density (robust + no extra deps)
    ax.hist(Za, bins=bins, density=True, alpha=0.5, label=f"mode {alpha}")
    ax.hist(Zb, bins=bins, density=True, alpha=0.5, label=f"mode {beta}")

    ax.set_title("LDA projection density")
    ax.set_xlabel("LDA 1D projection")
    ax.set_ylabel("density")
    ax.legend()
    fig.tight_layout()
    return ax

def plot_dmin_scatter(mean_ks, dmins, *, ax: Optional[plt.Axes] = None) -> plt.Axes:
    if ax is None:
        fig, ax = plt.subplots(figsize=(6, 4))
    ax.scatter(mean_ks, dmins)
    ax.set_xlabel("<k>")
    ax.set_ylabel("d'_min")
    ax.set_title("Nearest-neighbor discriminability (Bernoulli HMM)")
    return ax