# -*- coding: utf-8 -*-
"""dominance_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQMugIRnUzBfRAd8Q6AfUDNxNgGg2y2K
"""

from __future__ import annotations
import numpy as np
import matplotlib.pyplot as plt

def plot_theta_scan(thetas, avg_cells_per_mode, avg_modes_per_cell):
    thetas = np.asarray(thetas, dtype=float)
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(thetas, avg_cells_per_mode, marker="o")
    ax.set_xlabel(r"threshold $\theta$")
    ax.set_ylabel("avg #cells per mode")
    ax.set_title("Average number of dominated cells per mode")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    return fig, ax

def plot_theta_scan_modes_per_cell(thetas, avg_modes_per_cell):
    thetas = np.asarray(thetas, dtype=float)
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(thetas, avg_modes_per_cell, marker="o")
    ax.set_xlabel(r"threshold $\theta$")
    ax.set_ylabel("avg #modes per cell")
    ax.set_title("Average number of modes a cell belongs to")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    return fig, ax

def plot_modes_per_cell_hist(modes_per_cell, theta_star: float):
    modes_per_cell = np.asarray(modes_per_cell, dtype=int)
    bins = np.arange(0, modes_per_cell.max() + 2) - 0.5

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(modes_per_cell, bins=bins, alpha=0.8, edgecolor="black")
    ax.set_xlabel("# modes a cell belongs to")
    ax.set_ylabel("# cells")
    ax.set_title(rf"Modes per cell at $\theta={theta_star}$")
    fig.tight_layout()
    return fig, ax

def plot_cells_per_mode_bar(cells_per_mode, theta_star: float, sort_desc: bool = True):
    cells_per_mode = np.asarray(cells_per_mode, dtype=int)
    K = cells_per_mode.size

    if sort_desc:
        order = np.argsort(-cells_per_mode)
        values = cells_per_mode[order]
        xticklabels = order
        xlabel = "mode index (sorted by size)"
    else:
        values = cells_per_mode
        xticklabels = np.arange(K)
        xlabel = "mode index"

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(np.arange(K), values, edgecolor="black", alpha=0.85)
    ax.set_xticks(np.arange(K))
    ax.set_xticklabels(xticklabels)
    ax.set_xlabel(xlabel)
    ax.set_ylabel("# dominated cells")
    ax.set_title(rf"Dominated cells per mode at $\theta={theta_star}$")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    return fig, ax