# -*- coding: utf-8 -*-
"""dwell_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMts1i2wWqjKnv6IdKqbEqZw6YgS0g5H
"""

from __future__ import annotations
import numpy as np
import matplotlib.pyplot as plt
import math
from typing import List

def plot_dwell_histograms(
    dwell_times_per_mode: List[np.ndarray],
    *,
    max_cols: int = 5,
    bins: int = 15,
):
    """
    Plot dwell time histograms for each mode.

    Parameters
    ----------
    dwell_times_per_mode : list of np.ndarray
        Output of compute_dwell_times.
    max_cols : int
        Maximum number of columns per row.
    bins : int
        Number of histogram bins.
    """
    K = len(dwell_times_per_mode)
    if K == 0:
        raise ValueError("No modes to plot")

    n_cols = min(K, max_cols)
    n_rows = math.ceil(K / n_cols)

    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(3 * n_cols, 2.5 * n_rows),
        sharex=False,
        sharey=False
    )

    axes = np.atleast_2d(axes)

    for k in range(K):
        row = k // n_cols
        col = k % n_cols
        ax = axes[row, col]

        dt_k = dwell_times_per_mode[k]
        n_segments = len(dt_k)

        if n_segments > 0:
            ax.hist(dt_k, bins=bins, edgecolor="black", alpha=0.7)

        ax.set_title(f"Mode {k}\n(n={n_segments})", fontsize=16)
        ax.tick_params(axis="both", labelsize=16)


        if row == n_rows - 1:
            ax.set_xlabel("Dwell time (s)", fontsize=18)
        if col == 0:
            ax.set_ylabel("Count", fontsize=18)

    # remove unused axes
    for k in range(K, n_rows * n_cols):
        row = k // n_cols
        col = k % n_cols
        fig.delaxes(axes[row, col])

    plt.tight_layout()
    return fig