# -*- coding: utf-8 -*-
"""mapping_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0y9QqVZKMQ8FeF2QRZSalDkd5AixJWm
"""

from __future__ import annotations

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

def _get_pos(index_to_spatial, cell_idx):
    info = index_to_spatial.get(cell_idx, None)
    if info is None:
        return None
    pos = info.get("pos", None)
    return pos

def plot_mode_spatial_scatter(mode_k, dominated_mask, index_to_spatial, s=30, alpha=0.7, figsize=(4, 4)):
    xs, ys = [], []

    for cell_idx, is_dom in enumerate(dominated_mask[mode_k]):
        if not is_dom:
            continue
        pos = _get_pos(index_to_spatial, cell_idx)
        if pos is None:
            continue
        r, c = pos
        xs.append(c)
        ys.append(-r)

    plt.figure(figsize=figsize)
    plt.scatter(xs, ys, s=s, alpha=alpha)
    plt.title(f"Mode {mode_k}: Dominated cells")
    plt.axis("equal")
    plt.axis("off")
    plt.show()

def plot_mode_spatial_heatmap(
    mode_k,
    dominated_mask,
    index_to_spatial,
    grid_shape=(12, 12),
    cmap="Reds",
    figsize=(4, 4),
    cbar=True,
):
    # seaborn optional import guard
    try:
        import seaborn as sns
    except Exception as e:
        raise ImportError("seaborn is required for plot_mode_spatial_heatmap. `pip install seaborn`") from e

    heat = np.zeros(grid_shape, dtype=float)

    for cell_idx, is_dom in enumerate(dominated_mask[mode_k]):
        if not is_dom:
            continue
        pos = _get_pos(index_to_spatial, cell_idx)
        if pos is None:
            continue
        r, c = pos
        heat[r, c] += 1

    plt.figure(figsize=figsize)
    sns.heatmap(heat, cmap=cmap, square=True, cbar=cbar)
    plt.title(f"Mode {mode_k}: spatial density")
    plt.axis("off")
    plt.show()

def plot_mode_clusters_on_mea(
    mode_k,
    dominated_mask,          # (K, N)
    cell_cluster,            # (N,)
    index_to_spatial,
    channel_info,
    title=None,
    jitter_radius=0.20,
    legend_ncol=3,
    electrode_size=18,
    cell_size=70,
    alpha_cells=0.9,
):
    # 背景：电极
    elec_rc = [coord for coord, _ in channel_info]
    elec_r = np.array([rc[0] for rc in elec_rc])
    elec_c = np.array([rc[1] for rc in elec_rc])

    # 该 mode 的 dominated cells，按 (r,c) 分组，为了 jitter
    pos_to_cells = {}  # (r,c) -> list of cluster labels
    N = dominated_mask.shape[1]

    for cell_idx in range(N):
        if not dominated_mask[mode_k, cell_idx]:
            continue
        val = cell_cluster[cell_idx]

        # 1️⃣ 跳过 NaN
        if np.isnan(val):
            continue

        cl = int(val)
        if cl < 0:
            continue
        pos = _get_pos(index_to_spatial, cell_idx)
        if pos is None:
            continue
        r, c = pos
        pos_to_cells.setdefault((r, c), []).append(cl)

    if len(pos_to_cells) == 0:
        print(f"Mode {mode_k}: no dominated cells with valid cluster labels.")
        return

    clusters_in_mode = sorted({cl for cls in pos_to_cells.values() for cl in cls})
    cmap = plt.get_cmap("tab20", len(clusters_in_mode)) if len(clusters_in_mode) <= 20 else plt.get_cmap("hsv", len(clusters_in_mode))
    cl_to_color = {cl: cmap(i) for i, cl in enumerate(clusters_in_mode)}

    xs, ys, colors = [], [], []
    for (r, c), cls in pos_to_cells.items():
        m = len(cls)
        if m == 1:
            angles = [0.0]; radii = [0.0]
        else:
            angles = np.linspace(0, 2*np.pi, m, endpoint=False)
            radii = np.full(m, jitter_radius)

        for cl, ang, rr in zip(cls, angles, radii):
            xs.append(c + rr*np.cos(ang))
            ys.append(-r + rr*np.sin(ang))
            colors.append(cl_to_color[cl])

    plt.figure(figsize=(7, 7))
    plt.scatter(elec_c, -elec_r, s=electrode_size, alpha=0.25)
    plt.scatter(xs, ys, s=cell_size, c=colors, alpha=alpha_cells, edgecolors="none")

    handles = [
        Line2D([0], [0], marker='o', linestyle='', markersize=7,
               markerfacecolor=cl_to_color[cl], label=f"C{cl}")
        for cl in clusters_in_mode
    ]
    plt.legend(handles=handles, bbox_to_anchor=(1.02, 1), loc="upper left",
               title="Cluster (within this mode)", ncol=legend_ncol, frameon=False)

    plt.title(title or f"Mode {mode_k}: dominated cells colored by cluster (n={len(xs)})")
    plt.axis("equal"); plt.axis("off")
    plt.tight_layout()
    plt.show()