# -*- coding: utf-8 -*-
"""mode_cluster_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfxyM6zV-s7GFat7Wts6J-zzGGcnFCUP
"""

import matplotlib.pyplot as plt
import numpy as np

def plot_mode_cluster_heatmap(counts, unique_modes, unique_clusters, *, title="", figsize=(4,4), cmap="Blues"):
    fig, ax = plt.subplots(figsize=figsize)
    im = ax.imshow(counts, cmap=cmap, aspect="auto")

    ax.set_xticks(np.arange(len(unique_clusters)))
    ax.set_xticklabels(unique_clusters, rotation=45, ha="right")
    ax.set_xlabel("Cluster label")

    ax.set_yticks(np.arange(len(unique_modes)))
    ax.set_yticklabels(unique_modes)
    ax.set_ylabel("Mode")

    ax.set_title(title)
    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label("# dominated cells")

    plt.tight_layout()
    return fig, ax