# -*- coding: utf-8 -*-
"""mode_cluster_psth_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptyTZ6UtcRqFRRXSh_eVNj9OnR_30eCk
"""

from __future__ import annotations
import numpy as np
import matplotlib.pyplot as plt
from typing import Dict, Iterable, List, Tuple, Optional

from analysis.mode_cluster_psth import cluster_psth_templates_auto


def group_mode_contrast_by_cluster_for_cell(
    *,
    X: np.ndarray,
    modes: np.ndarray,
    contrast_per_bin: np.ndarray,
    cell: int,
    modes_to_show: Iterable[int],
    contrasts: Iterable[int],
    cluster_by_contrast: Dict[int, np.ndarray],
    require_spikes: bool = True,
    exclude_noise: bool = True,
) -> Dict[Tuple[int, int], List[int]]:
    """
    Returns dict: key=(contrast, cluster), value=sorted list of modes
    Only keeps panels where:
      - (mode, contrast) exists in time bins
      - and (optionally) cell fires at least once under that (mode, contrast)
      - and cluster label exists and is valid (not NaN; and >=0 if exclude_noise)
    """
    groups: Dict[Tuple[int, int], set] = {}

    for k in modes_to_show:
        for c in contrasts:
            mask_mc = (modes == int(k)) & (contrast_per_bin == int(c))
            if mask_mc.sum() == 0:
                continue
            if require_spikes and (X[mask_mc, cell].sum() <= 0):
                continue

            lab_arr = cluster_by_contrast[int(c)]
            if cell >= len(lab_arr):
                continue

            lab = lab_arr[cell]
            if np.isnan(lab):
                continue
            if exclude_noise and (lab < 0):
                continue
            cl = int(lab)

            groups.setdefault((int(c), cl), set()).add(int(k))

    return {key: sorted(list(v)) for key, v in groups.items()}

def plot_cell_cluster_templates_with_modes_in_title(
    *,
    X: np.ndarray,
    tau: np.ndarray,
    modes: np.ndarray,
    contrast_per_bin: np.ndarray,
    cell: int,
    modes_to_show: Iterable[int],
    cluster_by_contrast: Dict[int, np.ndarray],
    contrasts: Iterable[int] = (50, 60, 70, 80, 90),
    dt: float = 0.05,
    t_min: float = 0.0,
    t_max: float = 3.0,
    ncols: int = 4,
    require_spikes: bool = True,
    exclude_noise: bool = True,
    title_prefix: Optional[str] = None,
):
    """
    One panel per (contrast, cluster). Plot the cluster template PSTH.
    Title includes all modes for which this cell is active and belongs to that cluster.
    """
    groups = group_mode_contrast_by_cluster_for_cell(
        X=X,
        modes=modes,
        contrast_per_bin=contrast_per_bin,
        cell=cell,
        modes_to_show=modes_to_show,
        contrasts=contrasts,
        cluster_by_contrast=cluster_by_contrast,
        require_spikes=require_spikes,
        exclude_noise=exclude_noise,
    )

    if len(groups) == 0:
        print("No drawable panels (inactive/filtered/no valid cluster).")
        return None, None

    keys = sorted(groups.keys())  # sort by (contrast, cluster)
    n = len(keys)
    nrows = int(np.ceil(n / ncols))

    fig, axes = plt.subplots(nrows, ncols, figsize=(3*ncols, 2.4*nrows),
                             sharex=True, sharey=True)
    axes = np.array(axes).reshape(-1)

    for ax_i, (c, cl) in enumerate(keys):
        ax = axes[ax_i]

        t, templ = cluster_psth_templates_auto(
            X, tau,
            cell_cluster=cluster_by_contrast[c],
            dt=dt, t_min=t_min, t_max=t_max,
            contrast=c, contrast_per_bin=contrast_per_bin
        )

        if cl >= templ.shape[0] or np.all(np.isnan(templ[cl])):
            ax.set_axis_off()
            continue

        ax.plot(t, templ[cl])

        mode_list = groups[(c, cl)]
        mode_str = ", ".join(map(str, mode_list)) if len(mode_list) <= 10 else (", ".join(map(str, mode_list[:10])) + ", ...")
        ax.set_title(f"{c}%  C{cl}\nModes: {mode_str}", fontsize=9)

    for ax in axes[n:]:
        ax.set_axis_off()

    supt = f"Cell {cell}"
    if title_prefix:
        supt = f"{title_prefix} — {supt}"
    fig.suptitle(supt, y=1.02)
    plt.tight_layout()
    return fig, axes