# -*- coding: utf-8 -*-
"""mode_plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufzVfN0d0_cQFNFiXmYEyE4xH4UlMqX4
"""

from __future__ import annotations
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

# -----------------------------
# Global style
# -----------------------------
mpl.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Arial", "Liberation Sans", "Helvetica", "DejaVu Sans"],
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "axes.linewidth": 0.8,
    "xtick.major.width": 0.8,
    "ytick.major.width": 0.8,
    "xtick.major.size": 3,
    "ytick.major.size": 3,
})

# ---------------------------------------------------
# These sizes are chosen so that AFTER shrinking
# in the final composite/PDF, axis labels look ~12 pt
# ---------------------------------------------------
LABEL_SIZE = 18        # final visible ~12 pt after shrink
TICK_SIZE = 16         # final visible ~10-11 pt
PANEL_TITLE_SIZE = 12  # final visible ~8 pt

FIG_W = 4.0
FIG_H = 3.0


def _style_ax(ax, xlabel=None, ylabel=None, title=None):
    if xlabel is not None:
        ax.set_xlabel(xlabel, fontsize=LABEL_SIZE)
    if ylabel is not None:
        ax.set_ylabel(ylabel, fontsize=LABEL_SIZE)
    if title is not None:
        ax.set_title(title, fontsize=PANEL_TITLE_SIZE, pad=4)

    ax.tick_params(axis="both", labelsize=TICK_SIZE)
    for spine in ax.spines.values():
        spine.set_linewidth(0.8)


def plot_mode_probabilities(w_sorted: np.ndarray, title: str | None = None):
    w_sorted = np.asarray(w_sorted, dtype=float)
    K = w_sorted.size

    fig, ax = plt.subplots(figsize=(FIG_W, FIG_H))
    ax.bar(np.arange(1, K + 1), w_sorted, width=0.8)

    _style_ax(
        ax,
        xlabel="Mode # (sorted by weight)",
        ylabel="Mode prob. (w)",
        title=title
    )
    ax.set_ylim(0, 0.3)

    fig.tight_layout(pad=0.8)
    return fig, ax


def plot_entropy_vs_kbar(k_bar: np.ndarray, S_bits_s: np.ndarray, title: str | None = None):
    k_bar = np.asarray(k_bar, dtype=float)
    S_bits_s = np.asarray(S_bits_s, dtype=float)

    fig, ax = plt.subplots(figsize=(FIG_W, FIG_H))
    ax.scatter(k_bar, S_bits_s, s=40)

    _style_ax(
        ax,
        xlabel="Avg. spike count <k>",
        ylabel="Mode entropy (bits/s)",
        title=title
    )

    fig.tight_layout(pad=0.8)
    return fig, ax


def plot_normalized_entropy(k_bar: np.ndarray, ratio: np.ndarray, title: str | None = None):
    k_bar = np.asarray(k_bar, dtype=float)
    ratio = np.asarray(ratio, dtype=float)

    fig, ax = plt.subplots(figsize=(FIG_W, FIG_H))
    ax.scatter(k_bar, ratio, s=40)

    _style_ax(
        ax,
        xlabel="Avg. spike count <k>",
        ylabel=r"$S_{\max}/S$",
        title=title
    )
    ax.set_ylim(0, 3)

    fig.tight_layout(pad=0.8)
    return fig, ax