# -*- coding: utf-8 -*-
"""stat_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185CZjJHFtzKR_Y1qxEIrshdO4SO_fTtt
"""

from __future__ import annotations
import numpy as np
import matplotlib.pyplot as plt

def plot_binned_comparison(
    x_mean, y_mean, x_std, y_std, n_bin,
    xlabel: str, ylabel: str, title: str,
):
    """
    Generic binned scatter with x/y errorbars + 95% CI band on y.
    Returns fig, ax.
    """
    x_mean = np.asarray(x_mean, float)
    y_mean = np.asarray(y_mean, float)
    x_std  = np.asarray(x_std, float)
    y_std  = np.asarray(y_std, float)
    n_bin  = np.asarray(n_bin, int)

    sem = y_std / np.sqrt(np.maximum(n_bin, 1))
    ci_upper = y_mean + 1.96 * sem
    ci_lower = y_mean - 1.96 * sem

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.fill_between(x_mean, ci_lower, ci_upper, alpha=0.2)
    ax.errorbar(
        x_mean, y_mean,
        xerr=x_std, yerr=y_std,
        fmt="o", capsize=3, alpha=0.9, ecolor="black"
    )

    min_val = min(x_mean.min(), y_mean.min())
    max_val = max(x_mean.max(), y_mean.max())
    ax.plot([min_val, max_val], [min_val, max_val], "k--")

    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    fig.tight_layout()
    return fig, ax

