## -*- coding: utf-8 -*-
"""transitions_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVZ5ySxXr1TqSnuKiI3E4AxptI2xS9X0
"""

from __future__ import annotations
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
import networkx as nx

# -----------------------------------
# Same style as the previous figures
# -----------------------------------
mpl.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Arial", "Liberation Sans", "Helvetica", "DejaVu Sans"],
    "axes.linewidth": 0.8,
    "xtick.major.width": 0.8,
    "ytick.major.width": 0.8,
    "xtick.major.size": 3,
    "ytick.major.size": 3,
})

LABEL_SIZE = 18
TICK_SIZE = 16
TITLE_SIZE = 12
LEGEND_SIZE = 11
CBAR_TICK_SIZE = 14

# sizes chosen to match your previous workflow
FIG_W = 4.0
FIG_H = 3.0
WIDE_W = 8.2
WIDE_H = 4.0
GRAPH_W = 5.5
GRAPH_H = 5.5


def save_png(fig, filename: str, dpi: int = 300):
    fig.savefig(filename, dpi=dpi, bbox_inches="tight")


def plot_transition_matrices(
    A,
    A_off,
    cmap="hot",
    tick_step=5,
    figsize=(WIDE_W, WIDE_H),
):
    K = A.shape[0]
    fig, axes = plt.subplots(1, 2, figsize=figsize, constrained_layout=True)

    ticks = np.arange(0, K, tick_step)

    for ax, M in [
        (axes[0], A),
        (axes[1], A_off),
    ]:
        im = ax.imshow(M, cmap=cmap, interpolation="nearest", aspect="equal")

        ax.set_xlabel("Next mode", fontsize=LABEL_SIZE)
        ax.set_ylabel("Current mode", fontsize=LABEL_SIZE)

        ax.set_xticks(ticks)
        ax.set_yticks(ticks)
        ax.set_xticklabels(ticks)
        ax.set_yticklabels(ticks)

        ax.tick_params(axis="x", labelsize=TICK_SIZE, pad=2)
        ax.tick_params(axis="y", labelsize=TICK_SIZE, pad=2)

        cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03)
        cbar.ax.tick_params(labelsize=CBAR_TICK_SIZE)

        for spine in ax.spines.values():
            spine.set_linewidth(0.8)

    return fig, axes


def plot_transition_entropy_vs_kbar(
    k_bar,
    H_all,
    H_off,
    K,
    ax_width=4.0,     # 主图宽度
    ax_height=3.0,    # 主图高度
    legend_space=1.8, # 右侧专门留给 legend 的宽度
    show_legend=True,
):
    # 整张 figure 变宽，但左边主图大小不变
    fig = plt.figure(figsize=(ax_width + legend_space, ax_height))

    # [left, bottom, width, height] in figure fraction
    # 这里把主图固定在左边，不让它被 legend 挤压
    ax = fig.add_axes([
        0.12,                         # left
        0.18,                         # bottom
        ax_width / (ax_width + legend_space) * 0.80,   # width
        0.70                          # height
    ])

    ax.scatter(k_bar, H_all, marker="v", s=80, label="All elements")
    ax.scatter(k_bar, H_off, marker="^", s=80, label="Off-diagonal")
    ax.axhline(np.log2(K), linestyle="--", color="black", label="maximum")

    ax.set_ylim(-1, 5)
    ax.set_yticks(range(0, 6))

    ax.set_xlabel("Avg. spike count <k>", fontsize=LABEL_SIZE)
    ax.set_ylabel("Entropy H (bits)", fontsize=LABEL_SIZE)

    ax.tick_params(axis="x", labelsize=TICK_SIZE)
    ax.tick_params(axis="y", labelsize=TICK_SIZE)

    for spine in ax.spines.values():
        spine.set_linewidth(0.8)

    if show_legend:
        ax.legend(
            fontsize=LEGEND_SIZE,
            loc="upper left",
            bbox_to_anchor=(1.02, 1.0),
            borderaxespad=0,
            frameon=False
        )

    return fig, ax

def plot_transition_graph(
    P,
    modes,
    K,
    th=0.05,
    seed=0,
    figsize=(GRAPH_W, GRAPH_H),
    label_fontsize=14,
    node_scale=6000,
    edge_scale=8,
    k_layout=1.2,
    node_boost=1.4,
    edge_thin=0.35,
    arrowsize_normal=5,
    normal_edge_color="black",
    normal_edge_alpha=0.9,
    normal_rad=0.05,
    label_stroke=3.5,
    label_pad_pts=8,
    digit_pad_pts=4,
    font_family="Arial",
):
    # occupancy
    counts = np.bincount(modes, minlength=K)
    occ = counts / counts.sum()

    # graph
    G = nx.DiGraph()
    for k in range(K):
        G.add_node(k, weight=float(occ[k]))

    for i in range(K):
        for j in range(K):
            if i != j and P[i, j] > th:
                G.add_edge(i, j, weight=float(P[i, j]))

    pos = nx.spring_layout(G, seed=seed, k=k_layout)

    node_sizes = {
        k: node_scale * node_boost * G.nodes[k]["weight"]
        for k in G.nodes()
    }

    normal_edges = list(G.edges())

    fig, ax = plt.subplots(figsize=figsize)

    nx.draw_networkx_nodes(
        G,
        pos,
        node_size=[node_sizes[k] for k in G.nodes()],
        node_color="skyblue",
        edgecolors="k",
        linewidths=0.8,
        ax=ax,
    )

    if len(normal_edges) > 0:
        normal_widths = [
            edge_scale * edge_thin * G[u][v]["weight"]
            for u, v in normal_edges
        ]
        nx.draw_networkx_edges(
            G,
            pos,
            edgelist=normal_edges,
            width=normal_widths,
            edge_color=normal_edge_color,
            alpha=normal_edge_alpha,
            arrows=True,
            arrowsize=arrowsize_normal,
            arrowstyle="-|>",
            connectionstyle=f"arc3,rad={normal_rad}",
            ax=ax,
        )

    for k, (x, y) in pos.items():
        r_pts = np.sqrt(node_sizes[k] / np.pi)

        vx, vy = x, y
        norm = np.hypot(vx, vy)
        if norm < 1e-8:
            vx, vy = 1.0, 0.0
            norm = 1.0
        ux, uy = vx / norm, vy / norm

        text = str(k)
        extra_pad = digit_pad_pts * (len(text) - 1)

        dx = 3 * (r_pts + label_pad_pts + extra_pad) * ux
        dy = 3 * (r_pts + label_pad_pts + extra_pad) * uy

        txt = ax.annotate(
            text,
            xy=(x, y),
            xytext=(dx, dy),
            textcoords="offset points",
            ha="center",
            va="center",
            fontsize=label_fontsize,
            fontfamily=font_family,
            fontweight="bold",
            color="black",
        )

        txt.set_path_effects([
            pe.Stroke(linewidth=label_stroke, foreground="white"),
            pe.Normal(),
        ])

    ax.axis("off")
    ax.margins(0.25)
    fig.tight_layout(pad=0.8)

    return fig, ax